- pkg/config/generate.go
Fixes https://github.com/jim-minter/azure-helm/issues/22
Also seems to fix https://github.com/jim-minter/azure-helm/issues/21
Fixes https://github.com/jim-minter/azure-helm/issues/21
(added by jim-minter)
> Add CCP service dns name in SC certificate

- pkg/helm/chart/templates/Deployment.apps/servicecatalog-api.yaml
- pkg/helm/chart/templates/Deployment.apps/servicecatalog-controller.yaml
@jim-minter @pweil- this PR adds the SC controller manager which comes up successfully - we still need to fix the cluster service broker resource urls and of course deploy the service broker deployments.
Fixes https://github.com/jim-minter/azure-helm/issues/10
> Run SC controller manager in HCP

- create.sh
- delete.sh
- tools/aad.sh
re-enables AAD login :-)
@pweil- @kargakis
> re-add aad support

- cmd/healthcheck/healthcheck.go
- pkg/api/api.go
- pkg/healthcheck/healthcheck.go
- pkg/plugin/plugin.go
> add simple health check which waits for the console to be ready

- pkg/tunnel/tunnel.go
@mjudeikis I'm not sure how you managed to run create.sh to completion with scalesets without this fix?
> fix tunnel to work with scalesets

- pkg/config/generate.go
- pkg/validate/validate.go
Initial draft to add OSE images function to resolve images
ToDo:
[ ] - confirm version after release.
[ ] - configure pre-release registry for testing before release
[ ] - pending on rhel image build to be working (other story)
> add ose image resolver

- env.example
> Use centos as default until rhel is working

- pkg/config/generate.go
Should be merged once the cherrypick of https://github.com/openshift/service-catalog/pull/11 gets merged.
> Use stock SC apiserver image once again

- pkg/helm/chart/templates/Deployment.apps/bootstrap-autoapprover.yaml
- pkg/helm/chart/templates/Deployment.apps/master-api.yaml
- pkg/helm/chart/templates/Deployment.apps/master-controllers.yaml
- pkg/helm/chart/templates/Deployment.apps/master-etcd.yaml
- pkg/helm/chart/templates/Deployment.apps/servicecatalog-api.yaml
- pkg/helm/chart/templates/Deployment.apps/sync.yaml
> replace checksum/ with checksum/secret in helm

- pkg/config/generate.go
Change pre-release etcd image version to hardcoded.
> change etcd image version

- env.example
@jim-minter until we fix it to work in a pod
> Default to run sync locally

- pkg/addons/client.go
- pkg/checks/checks.go
- pkg/healthcheck/healthcheck.go
Enhance the healthcheck to ensure the following:
1. The healthz check for the API returns a 200
2. The pods are in a Running state without restarts
3. The web console is available
@jim-minter, Please review
> Enhance the healthcheck to provide healthz for api and check for pod status to be running. 

- env.example
align to image versioning as we publish. 
alternative to republish all images
> remove v from image name

- pkg/addons/client.go
> fix addons race condition

- pkg/checks/checks.go
Fixes https://github.com/openshift/openshift-azure/issues/124
@jim-minter @kwoodson @mjudeikis
> Avoid nil resp panic

- hack/validate-generated.sh
> Fix validation script

- glide.lock
- glide.yaml
- vendor/k8s.io/api/Godeps/Godeps.json
- vendor/k8s.io/api/core/v1/generated.proto
- vendor/k8s.io/api/core/v1/types.go
- vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
- vendor/k8s.io/client-go/Godeps/Godeps.json
- vendor/k8s.io/kube-aggregator/Godeps/Godeps.json
> Pin kubernetes dependencies used directly by us

- pkg/validate/validate_test.go
Adding unit tests for the `pkg/validate`.
> Addings tests for pkg/validate.

- Makefile
- pkg/api/types.go
@amanohar
@openshift/sig-azure 
Follow up for https://github.com/openshift/openshift-azure/pull/143#discussion_r207299797
Also adds build as a default target in Makefile
> Remove unused extension type

- OWNERS
@openshift/sig-azure 
@shrutir25 fyi
> Add shrutir25 as a reviewer

- Makefile
- hack/validate-deps.sh
Fixes https://github.com/openshift/openshift-azure/issues/147
Note that we still need to pin some dependencies in glide.yaml - will open a separate issue for that.
> Check-in dep validation script

- hack/create.sh
Fix https://github.com/openshift/openshift-azure/issues/186 for dev/test process.
In the code we want DNS to be a permanent error.
> DNS fix for dev

- hack/create.sh
move to healthz checking for api server availability. 
@kargakis this still fails with random other errors sometimes. I think this is the best way for now for dev and test. What do you think?
> change from DNS to healthcheck

- glide.lock
- pkg/api/plugin.go
- pkg/plugin/plugin.go
- vendor/github.com/dimchansky/utfbom/go.mod
Split out of https://github.com/openshift/openshift-azure/pull/138
>  Add interface for VM readiness checks 

- cmd/createorupdate/createorupdate.go
- cmd/healthcheck/healthcheck.go
- cmd/sync/sync.go
- pkg/addons/addons.go
- pkg/api/converterfromosaapi.go
- pkg/api/converterfromosaapi_test.go
- pkg/api/convertertoosaapi.go
- pkg/api/convertertoosaapi_test.go
- pkg/api/plugin.go
- pkg/api/types.go
- pkg/api/v1/types.go
- pkg/api/v1/types_test.go
- pkg/arm/arm.go
- pkg/checks/checks.go
- pkg/config/generate.go
- pkg/config/generate_test.go
- pkg/config/upgrade.go
- pkg/healthcheck/client.go
- pkg/healthcheck/healthcheck.go
- pkg/plugin/plugin.go
- pkg/util/util.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
Fixes https://github.com/openshift/openshift-azure/issues/149
> Api cleanup

- pkg/config/generate.go
Reverts openshift/openshift-azure#191
@kwoodson
> Revert "Updating since origin sku was removed."

- cmd/createorupdate/createorupdate.go
- cmd/healthcheck/healthcheck.go
- cmd/sync/sync.go
- hack/create.sh
- hack/upgrade.sh
- added command line switch "loglevel" that  adjusts log level in a human readable way
- adjusted scripts to use it with loglevel=debug
> added human readable logging level flag

- Makefile
- hack/validate-vendor.sh
@kargakis @mjudeikis is doing this worthwhile?
> ensure that all prerequisite packages are vendored

- pkg/validate/validate.go
- pkg/validate/validate_test.go
Let's get some tests in there :+1:
> validation unit tests

- cmd/createorupdate/createorupdate.go
- cmd/healthcheck/healthcheck.go
- cmd/sync/sync.go
- pkg/log/log.go
@openshift/sig-azure tbh I am not in love with our log package at its current form but consolidating sanitizeLogLevel in there made sense.
> Logging cleanup

- pkg/config/generate.go
- pkg/config/generate_test.go
- pkg/plugin/plugin_test.go
- pkg/util/fixtures/fixtures.go
tests for generation setting the required fields
tests for merge of old/new config
> test generation required fields and merge

- pkg/config/generate.go
Adding `rhel7` as an option if set in env file.
> Add rhel7 as an option for env var DEEPLOY_OS

- cmd/logbridge/README.md
Fixes https://github.com/openshift/openshift-azure/issues/275
> Document systemd-devel dep

- hack/create.sh
> hide var checking

- hack/upgrade.sh
Similar to https://github.com/openshift/openshift-azure/pull/279 for upgrade
> Require and hide SP creds in upgrade.sh

- cmd/createorupdate/createorupdate.go
- cmd/createorupdate/deploy.go
- cmd/createorupdate/update.go
- pkg/api/types.go
> correct TenantID spelling

- pkg/addons/addons.go
- pkg/addons/addons_test.go
- pkg/addons/client.go
- pkg/addons/client_test.go
- pkg/addons/testdata/secret1.yaml
- pkg/addons/testdata/secret2.yaml
- pkg/addons/testdata/secret3.yaml
- pkg/addons/testdata/service1.yaml
- pkg/addons/testdata/service2.yaml
- pkg/addons/testdata/service3.yaml
Fixes https://github.com/openshift/openshift-azure/issues/266
> Fix restarts on services that use multiple config keys

- hack/create.sh
> remove output

- cmd/createorupdate/createorupdate.go
- hack/create.sh
- pkg/api/2018-09-30-preview/api/types.go
- pkg/config/generate.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
This should do. testing now if we don't have any fallouts from this 
cc: @jim-minter 
fixes #307
> self-sign console bug

- pkg/api/deepcopy.go
- pkg/api/deepcopy_test.go
- pkg/api/marshal.go
- pkg/config/generate_test.go
- pkg/util/fixtures/fixtures.go
> implement DeepCopy for OpenShiftManagedCluster

- pkg/api/deepcopy_test.go
Follow-up to https://github.com/openshift/openshift-azure/pull/315
> TestDeepCopy test after mutation

- pkg/plugin/plugin.go
Fixes https://github.com/openshift/openshift-azure/issues/193
> Deep copy old config before merging

- cmd/sync/sync.go
- pkg/log/log.go
verified locally that:
- it gives the expected output
> ./sync 
INFO[2018-09-03T15:10:19+02:00] Sync process started                       
- make test - tests pass
Fixes https://github.com/openshift/openshift-azure/issues/223
> enabling timestamps in sync

- cmd/createorupdate/update.go
Fixes https://github.com/openshift/openshift-azure/issues/281
> Avoid in-place updates for compute/infra nodes

- pkg/validate/validate.go
> must use %d not %q with ints

- README.md
- env.example
- hack/aad.sh
- hack/create.sh
- hack/delete.sh
This moves AAD integration to use Bring-your-own app model
> move to BYO AAD app flow

- cmd/createorupdate/createorupdate.go
- cmd/createorupdate/update.go
- cmd/createorupdate/update_test.go
- hack/create.sh
- hack/upgrade.sh
- pkg/plugin/plugin.go
- pkg/validate/validate.go
Ref https://jira.coreos.com/browse/AZURE-102
Fixes https://github.com/openshift/openshift-azure/issues/285
> Enable scale up/down

- pkg/config/generate.go
> remove aadTenantId from cloud config

- README.md
- cmd/createorupdate/createorupdate.go
- hack/create.sh
- pkg/api/2018-09-30-preview/api/types.go
- pkg/api/2018-09-30-preview/api/types_test.go
- pkg/api/converterfromv20180930preview.go
- pkg/api/converterfromv20180930preview_test.go
- pkg/api/convertertov20180930preview.go
- pkg/api/convertertov20180930preview_test.go
- pkg/api/deepcopy_test.go
- pkg/api/types.go
- pkg/api/types_test.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
> remove ServicePrincipalProfile from external api

- cmd/createorupdate/createorupdate.go
- hack/create.sh
- hack/upgrade.sh
- pkg/api/plugin.go
- pkg/plugin/plugin.go
- pkg/upgrade/deploy.go
- pkg/upgrade/drain.go
- pkg/upgrade/update.go
- pkg/upgrade/update_test.go
Fixes https://github.com/openshift/openshift-azure/issues/334
> Add Update plugin method

- hack/config.sh
- pkg/api/config.go
- pkg/config/generate.go
- pkg/config/generate_test.go
- pkg/config/util.go
Adds temporary password for PP UI access.
cc: @openshift/sig-azure please tell me better way to store password temporary for our use? :) 
Fixes https://github.com/openshift/openshift-azure/issues/319
> Add generated htpasswd

- cmd/createorupdate/createorupdate.go
- pkg/api/plugin.go
- pkg/arm/arm.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
Fixes https://github.com/openshift/openshift-azure/issues/367
> GenerateARM signature uses a bool for indicating update

- pkg/upgrade/drain.go
- pkg/upgrade/ready.go
- pkg/upgrade/types.go
- pkg/upgrade/update.go
Ref https://github.com/openshift/openshift-azure/issues/362
@openshift/sig-azure ptal, seems like a quick win until we have the proposal @jim-minter is going to work post-PP.
> Sort master VMs by health before upgrade

- pkg/api/config.go
> added json tags to Config struct

- README.md
fixes: https://github.com/openshift/openshift-azure/issues/366
> add access the cluster section

- pkg/checks/checks.go
- test/e2e/osa_test.go
I'm not in love with this, but it may be pragmatic.  @pweil- @kargakis @mjudeikis wdyt?
> remove prometheus from health check, but add an e2e check

- test/overrides
depending on https://github.com/openshift/release/pull/1468 to go in first
> osa test blacklist

- docs/testing.md
add sub-document for how to work with tests in this repo
> add draft for test doc

- pkg/addons/addons.go
@kargakis @kwoodson @mjudeikis @pweil- I'm fairly confident this will help our PV timeout problem.  I'm pretty sure that part/all of it is a race between the statefulset controller creating PVCs and the default StorageClass having been created (note, alphabetically speaking StorageClass is just after StatefulSet).
> always create StorageClasses before objects that use them

- hack/ssh.sh
> clarify ssh.sh argument ordering

- pkg/upgrade/ready.go
for fullness, I think we should be doing this
@kargakis
> ensure master node is ready before moving on

- Makefile
> added a make vet target

- cmd/sync/sync.go
- pkg/addons/addons.go
- pkg/checks/checks.go
- pkg/upgrade/drain.go
- pkg/upgrade/ready.go
- pkg/util/wait/wait.go
also convert Polls to PollImmediates - saves a few seconds
@kargakis ptal
> don't wait 3 minutes if config blob read fails

- pkg/addons/bindata.go
- pkg/addons/data/ClusterRole.rbac.authorization.k8s.io/kube-state-metrics.yaml
- pkg/addons/data/Deployment.apps/openshift-metrics/kube-state-metrics.yaml
- pkg/addons/data/Role.rbac.authorization.k8s.io/openshift-metrics/kube-state-metrics-resizer.yaml
- pkg/addons/data/RoleBinding.rbac.authorization.k8s.io/openshift-metrics/kube-state-metrics.yaml
- pkg/addons/data/Service/openshift-metrics/kube-state-metrics.yaml
- pkg/addons/data/ServiceAccount/openshift-metrics/kube-state-metrics.yaml
- pkg/addons/translate.go
- pkg/api/config.go
- pkg/config/images.go
This adds kube-state metrics deployment to be scrapped and accessed
> add/enable kube-state metrics

- pkg/api/convertertov20180930preview.go
> don't set a slice capacity with a negative number

- Makefile
@mjudeikis @charlesakalugwu separate target/job is not needed. This should enable running vet in CI.
> Collapse vet target in verify

- pkg/addons/bindata.go
- pkg/addons/data/ClusterRoleBinding.rbac.authorization.k8s.io/kube-state-metrics-cluster-role-binding.yaml
@kargakis plat 
based on : https://github.com/kubernetes/kube-state-metrics/tree/master/kubernetes
solves: https://github.com/openshift/openshift-azure/issues/463
> add missing rbac kube-state-metrics

- pkg/config/generate.go
- pkg/config/images.go
- pkg/config/images_test.go
Parsing image version to determine correct version string.
fixes #465
> Parsing image version.

- pkg/util/fixtures/fixtures.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
> adds FQDN validation for cluster and for router

- pkg/addons/client.go
- pkg/healthcheck/healthcheck.go
- pkg/healthcheck/wait.go
> This is a simple move of checks/checks.go to healthcheck/wait.go

- OWNERS
> Add rest of OSA team in reviewers

- README.md
> Cluster access readme update

- env.example
- hack/create.sh
> Allow the region to be passed in

- hack/ssh.sh
so we could disable sync pod using this in ci as non-interactive mode
> ssh add ability to pass command

- cmd/sync/sync.go
- pkg/api/validate.go
- pkg/api/validate_test.go
- pkg/plugin/plugin.go
> Simple move of validate into the api package

- .gitignore
- Dockerfile.e2e
- Makefile
- test/e2e/extended_suite_test.go
- test/e2e/osa_test.go
@jim-minter @pweil- @mjudeikis @kwoodson this PR adds an image for our e2e tests.
> Create image with e2e tests

- Makefile
- hack/verify-code-format.sh
- pkg/api/default.go
- pkg/arm/arm.go
- pkg/config/generate.go
> Add gofmt, goimports and golint checks (fix existing issues)

- pkg/api/validate.go
- pkg/api/validate_test.go
> Add unit tests for validateUpdateContainerService

- pkg/api/validate.go
- pkg/api/validate_test.go
fixes #534 
@pweil- @mjudeikis @kargakis ptal.
@amanohar and I believe that we should backport this.
> validate cloudapp hostname using location and fix validation logic error

- test/e2e/osa_test.go
Was recently an issue (#429) but moved to a feature https://jira.coreos.com/browse/AZURE-153
> Adding tests for osa container images.

- hack/e2e.sh
Enable running end-user e2e tests as part of our merge queue.
Part of https://jira.coreos.com/browse/AZURE-144
> Enable end user e2e tests

- hack/e2e.sh
- test/e2e/client_test.go
- test/e2e/conditions_test.go
- test/e2e/end_user_test.go
Fixes https://github.com/openshift/openshift-azure/issues/309
> Add PDB e2e test

- hack/e2e.sh
- test/e2e/end_user_test.go
- test/e2e/generator_test.go
> Generate project names in e2e tests

- pkg/api/validate.go
- pkg/api/validate_test.go
Update our rfc1123 to match MSFT's rfc952.
Fixes #523
> Updated rfc1123 to rfc952.

- hack/scp.sh
scp wrapper to get node log, etc from the nodes
> add scp hack

- Makefile
adds logbridge target to be built in ci
> add logbridge promotion

- pkg/api/plugin.go
- pkg/arm/arm.go
- pkg/fakerp/fakerp.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- pkg/upgrade/deploy.go
- pkg/upgrade/types.go
- pkg/upgrade/update.go
> Replace azuredeploy []byte with template map[string]interface{}

- Makefile
- cmd/createorupdate/createorupdate.go
- env.example
- pkg/api/plugin.go
- pkg/config/images.go
- pkg/plugin/plugin_test.go
> Create versioned logbridge images and pass it into PluginConfig

- cmd/sync/sync.go
This PR updates the sync process to cache the storage client to avoid listing keys more than once to avoid getting ratelimited since the storage RP limits seem to be lower than other RP limits.
Closes https://github.com/openshift/openshift-azure/issues/606
> Cache storage client keys in sync

- hack/verify-code-format.sh
- pkg/config/util.go
- pkg/upgrade/drain_test.go
- pkg/util/mocks/mock_arm/arm.go
- pkg/util/mocks/mock_azureclient/mock_storage/storage.go
- pkg/util/mocks/mock_upgrade/types.go
@charlesakalugwu the automation we were talking about re import groups
> Automate splitting imports into three different groups

- test/e2e/end_user_test.go
Fixes #625
Change the template used, mongodb is playing the eventually consistent game. No need to change anything else, the web page shown has the same structure and the counter increments.
> Change test template

- cmd/createorupdate/createorupdate.go
- hack/delete.sh
> Support DELETE in the fake RP

- pkg/arm/arm.go
- pkg/upgrade/types.go
- pkg/util/azureclient/azureclient.go
- pkg/util/wait/wait.go
Should have been part of https://github.com/openshift/openshift-azure/pull/630
/cc @asalkeld
> Separate imports in generated code

- cmd/createorupdate/createorupdate.go
> defer cleanup of the cluster if it was requested

- hack/e2e.sh
- test/e2e/client_test.go
- test/e2e/end_user_test.go
- test/e2e/extended_suite_test.go
Should help debug https://github.com/openshift/openshift-azure/issues/643
/cc thekad
> Get debug info from end-user e2e tests

- pkg/addons/translate.go
- pkg/api/config.go
- pkg/config/generate.go
- pkg/config/generate_test.go
Fixes https://github.com/openshift/openshift-azure/issues/663
I'm not sure I trust this PR with the number.
> Adding RunningUnderTest to Config.

- cmd/createorupdate/createorupdate.go
Fixes https://github.com/openshift/openshift-azure/issues/605
> Retry connection refused errors

- pkg/fakerp/fakerp.go
- pkg/log/log.go
- pkg/util/azureclient/resources.go
> Get result from applied arm template

- pkg/api/plugin.go
- pkg/api/plugin_test.go
- pkg/plugin/plugin_test.go
- pkg/upgrade/deploy.go
- pkg/upgrade/healthcheck.go
- pkg/upgrade/ready.go
- pkg/upgrade/update.go
> Return a structured error in the plugin api so the step that failed is obvious

- pkg/config/generate.go
Fixes https://github.com/openshift/openshift-azure/issues/688
/assign kwoodson
> Make htpasswd setup re-entrant

- pkg/api/2018-09-30-preview/api/types_test.go
- pkg/api/types_test.go
- pkg/util/structtags/structtags.go
> test struct tags of the api types

- cmd/createorupdate/createorupdate.go
Fixes https://github.com/openshift/openshift-azure/issues/691
> Fix createorupdate error typecast panic

- pkg/config/images.go
as soon as we "go live" within cloud portal this image will be current "latest"
@jim-minter @kwoodson @kargakis @charlesakalugwu
> add published image

- cmd/createorupdate/createorupdate.go
> Gather artifacts in createorupdate

- pkg/api/plugin.go
- pkg/cluster/deploy.go
- pkg/cluster/healthcheck.go
- pkg/cluster/initialize.go
- pkg/cluster/initialize_test.go
- pkg/cluster/ready.go
- pkg/cluster/types.go
- pkg/cluster/update.go
- pkg/fakerp/fakerp.go
- pkg/plugin/plugin.go
- pkg/util/mocks/mock_cluster/types.go
Closes #694 
Simple change to return an opinionated structure instead of a plain error
> Return a PluginError instead of a plain error

- pkg/api/plugin.go
- pkg/cluster/deploy.go
- pkg/cluster/deploy_test.go
- pkg/cluster/initialize.go
- pkg/cluster/initialize_test.go
- pkg/cluster/update.go
- pkg/cluster/update_test.go
- pkg/log/log.go
Builds on top of https://github.com/openshift/openshift-azure/pull/670
Part of AZURE-199.
> Re-entrant node upgrades

- cmd/createorupdate/createorupdate.go
- env.example
- hack/create.sh
- hack/upgrade.sh
- pkg/fakerp/aad.go
- pkg/fakerp/config.go
- pkg/fakerp/manifest.go
- pkg/util/azureclient/graphrbac.go
- test/e2e.sh
- test/manifests/normal/create.yaml
This works for me now, although note it now requires we set AZURE_USERNAME and AZURE_PASSWORD.
Fixes https://github.com/openshift/openshift-azure/issues/618
> Rewrite hack/aad.sh in go

- cmd/createorupdate/createorupdate.go
- hack/create.sh
> Cleanup hack/create.sh

- pkg/cluster/deploy.go
- pkg/cluster/update.go
some small fixes to the logic of updates found during debugging
> Update hash fix

- cmd/createorupdate/createorupdate.go
Set AAD secret to client secret for tests
> add AADClientSecret

- cmd/createorupdate/createorupdate.go
- pkg/fakerp/config.go
- pkg/fakerp/manifest.go
> manifest default was not working using envconfig

- test/e2e/end_user_test.go
Fixes https://github.com/openshift/openshift-azure/issues/718
> always wait for route to return 200 before proceeding

- Makefile
- hack/validate-util.sh
- pkg/addons/translate.go
- pkg/arm/arm.go
- pkg/arm/arm_test.go
- pkg/fakerp/dns.go
- pkg/util/template/template.go
@jim-minter thoughts?
/cc jim-minter
> Validate pkg/util is empty

- pkg/config/images.go
bumpt to new release while we still can :)
> 3.11.43 release 

- pkg/cluster/deploy_test.go
> add unit tests for reading and updating the update blob

- pkg/cluster/deploy.go
- pkg/cluster/deploy_test.go
- pkg/cluster/initialize.go
- pkg/cluster/initialize_test.go
- pkg/cluster/ready_test.go
- pkg/cluster/types.go
- pkg/cluster/update.go
- pkg/cluster/update_test.go
- pkg/cluster/updateblob.go
- pkg/cluster/updateblob_test.go
fixes #786
tried to refactor and simplify this test and functional area - split out into smaller commits
> fix TestUpdateBlob flake

- pkg/addons/clean_test.go
- pkg/api/2018-09-30-preview/api/marshal.go
- pkg/api/2018-09-30-preview/api/types.go
- pkg/api/2018-09-30-preview/api/types_test.go
- pkg/api/converterfromv20180930preview.go
- pkg/api/converterfromv20180930preview_test.go
- pkg/api/convertertov20180930preview.go
- pkg/api/convertertov20180930preview_test.go
- pkg/api/deepcopy_test.go
- pkg/api/plugin.go
- pkg/api/types.go
- pkg/api/validate.go
- pkg/api/validate_test.go
- pkg/arm/arm_test.go
- pkg/cluster/ready_test.go
- pkg/config/derive_test.go
- pkg/config/generate_test.go
- pkg/config/images_test.go
- pkg/fakerp/dns.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/server.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- test/util/populate/walk.go
Part of AZURE-135
Fixes https://github.com/openshift/openshift-azure/issues/434
> Update external api to use pointers

- test/overrides
/cc @kargakis @charlesakalugwu
> remove overrides

- Makefile
@kargakis 
/hold
need to sync with release repo PR https://github.com/openshift/release/pull/2279
> add make target for metricsbridge

- pkg/cluster/updateblob.go
- pkg/cluster/updateblob_test.go
> Fix Md5Mismatch error during update in place

- test/e2e/specs/fakerp/admin.go
fixes https://github.com/openshift/openshift-azure/issues/842
> add prometheus operator components readiness check

- test/clients/openshift/client.go
- test/clients/openshift/login.go
seems better than hardcoded path.
> Use the new FindDirectory in e2e tests

- pkg/fakerp/dns.go
> remove extraneous -test on dns domain

- Makefile
- cmd/recoveretcdcluster/recoveretcdcluster.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/server.go
- test/clients/azure/osa.go
- test/e2e/specs/fakerp/keyrotation.go
> Key rotation e2e tests

- pkg/util/mocks/mock_kubeclient/types.go
@kargakis is master currently broken?  we don't retest as we merge code?
> fix stale generated code

- cmd/createorupdate/createorupdate.go
- pkg/fakerp/config.go
- pkg/fakerp/server.go
- test/clients/azure/client.go
Also add support for the admin api
/cc @kargakis
> Enable e2e to run against either fake rp or real rp.

- README.md
Added the go report card and godoc badges to the project readme. 
I'll also try to get the codecov badge + integration in this week.
/cc @openshift/sig-azure
> Add go-reportcard and godoc badges

- cmd/azure-controllers/azure-controllers.go
- cmd/recoveretcdcluster/recoveretcdcluster.go
- pkg/addons/addons.go
- pkg/addons/client.go
- pkg/addons/client_test.go
- pkg/arm/arm.go
- pkg/arm/arm_test.go
- pkg/controllers/customeradmin/namespace_controller.go
- pkg/controllers/customeradmin/rolebinding_controller.go
- pkg/controllers/customeradmin/shared.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/server.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- pkg/util/mocks/mock_arm/arm.go
- test/clients/azure/osa.go
- test/e2e/specs/fakerp/etcdrecovery.go
> Reordered arguments to match the ctx, log, ..., bool  order

- cmd/createorupdate/createorupdate.go
- pkg/api/2018-09-30-preview/api/client.go
- pkg/api/admin/api/client.go
- test/clients/azure/osa.go
- test/e2e/specs/fakerp/keyrotation.go
/cc charlesakalugwu 
Fixes https://github.com/openshift/openshift-azure/issues/807
> Key rotation e2e uses the OSA RP

- test/clients/azure/client.go
follow-up to #880 
/cc @kargakis @jim-minter
> Fix rp focus selections in e2e tests needing azure client

- OWNERS
@pweil- I hope you wont mind, you are still an approver.
> Remove pweil from reviewers

- pkg/api/plugin.go
- pkg/api/validate.go
- pkg/fakerp/dns.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/server.go
- pkg/plugin/plugin.go
This PR creates a new endpoint in the fake RP where the admin API is served
and enables handling of admin requests.
@jim-minter @charlesakalugwu 
Part of AZURE-119
> Support admin requests in the fake RP

- pkg/fakerp/config.go
> Relax dns variable restrictions from e2e tests

- Makefile
- test/e2e/specs/scaleupdown.go
- test/manifests/normal/scaledown.yaml
closes AZURE-117
it should be rebased after #794 is merged.
/cc @kargakis @mjudeikis 
/hold
> Scale up/down E2E tests

- test/e2e/specs/fakerp/admin.go
Fixes https://github.com/openshift/openshift-azure/issues/850
/cc @charlesakalugwu @jim-minter
> Change the order the monitoring stack is healthchecked

- pkg/fakerp/dns.go
- pkg/fakerp/fakerp.go
Part of https://github.com/openshift/azure-misc/issues/122
> Set ttl on dns zones

- pkg/api/validate.go
- pkg/api/validate_test.go
> issue-745 making router profile verification fail as soon as possible

- pkg/util/azureclient/azureclient.go
- pkg/util/azureclient/compute.go
- pkg/util/azureclient/graphrbac.go
- pkg/util/azureclient/managedapplications.go
- pkg/util/azureclient/marketplaceordering.go
- pkg/util/azureclient/resources.go
- pkg/util/azureclient/storage.go
by default it's 60 seconds, changed to 10
(also adds code which could be useful to debug azure HTTPS API calls - disabled by default)
> decrease polling interval

- .gitignore
- cmd/createorupdate/createorupdate.go
- cmd/fakerp/main.go
- cmd/recoveretcdcluster/recoveretcdcluster.go
- hack/create.sh
- hack/delete.sh
- hack/fakerp.sh
- hack/upgrade.sh
- pkg/fakerp/client/aad.go
- pkg/fakerp/client/config.go
- pkg/fakerp/client/manifest.go
- pkg/fakerp/config.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/server.go
- pkg/fakerp/shared/directory.go
- pkg/fakerp/shared/directory_test.go
- pkg/fakerp/shared/shared.go
- test/clients/azure/client.go
- test/clients/openshift/client.go
- test/clients/openshift/login.go
- test/e2e/specs/fakerp/admin.go
- test/e2e/specs/fakerp/etcdrecovery.go
- test/e2e/specs/fakerp/keyrotation.go
- test/e2e/specs/realrp/realrp.go
- test/e2e/specs/scaleupdown.go
Fixes https://github.com/openshift/openshift-azure/issues/912
> Split fake RP into its own process

- pkg/api/validate.go
- pkg/arm/arm_test.go
- pkg/cluster/deploy.go
- pkg/cluster/deploy_test.go
- pkg/cluster/ready_test.go
- pkg/cluster/update.go
- pkg/cluster/update_test.go
- pkg/config/derive.go
- pkg/config/derive_test.go
- pkg/config/names.go
- pkg/config/names_test.go
> Make the generation of scaleset and instance names more consistent

- Makefile
- pkg/api/validate.go
- pkg/api/validate_test.go
- pkg/util/azureclient/network.go
- pkg/util/azureclient/resources.go
- test/clients/azure/client.go
- test/e2e/specs/realrp/vnetpeering.go
Adding ability to precreate the vnet for vnet testing purposes.
> Add support for vnet testing

- pkg/fakerp/client/config.go
- test/e2e/specs/realrp/vnetpeering.go
> Vnet peering test updates

- Makefile
Should fix a lot of the kube-state timeouts we are seeing currently 
/cc @mjudeikis @charlesakalugwu
> Extend e2e test timeout

- pkg/api/types_test.go
Fixes #933 
Not sure if the AuthProfile.IdentityProviders Secret field should be missing from the internal representation. The test ignores that difference for now.
> added a parity test between 20180930preview and internal API

- hack/create.sh
- hack/delete.sh
- hack/upgrade.sh
/cc @charlesakalugwu 
Fixes https://github.com/openshift/openshift-azure/issues/953
> Wait specifically for lsof to exit

- Makefile
Add make targets so we could simplify templates
This will help to add things like "populate-template" for https://github.com/openshift/openshift-azure/pull/922
will fix release repo post merge
/cc @kargakis @charlesakalugwu
> add make delete create

- .gitignore
- docs/e2e/README.md
- docs/e2e/requirements.md
- docs/testing.md
- hack/e2e.sh
Please let me know if I am missing something.
closes #868 
/cc @kargakis
> Add documentation on e2e inputs and running with container image

- pkg/cluster/healthcheck.go
- test/e2e/specs/fakerp/admin.go
add some missing checks for cluster handover and tests
> add console and node-exporter checks

- pkg/api/converterfromadmin.go
- pkg/api/converterfromv20180930preview.go
- pkg/api/converterfromv20180930preview_test.go
- pkg/api/convertertoadmin.go
- pkg/api/convertertov20180930preview.go
- pkg/api/types.go
> replacing strings in internal representation ResourcePurchasePlan with pointers

- OWNERS
Add myself to the OWNERS's list.
> Add y-cote to reviewers list.

- pkg/fakerp/server.go
This change should help in writting more robust e2e tests where we can use GET OSA before applying a change in order to enable comparisons of the state of an OSA resource before and after an update from a client's POV.
/cc @charlesakalugwu @mjudeikis
> Enable fake RP GETs to work ootb

- test/e2e/specs/fakerp/admin.go
Enables the re-entrancy test to work with the production RP in the future.
> Use the RP instead of local file to get cluster state

- pkg/api/2018-09-30-preview/api/types.go
- pkg/api/admin/api/types.go
- pkg/api/converterfromadmin.go
- pkg/api/converterfromv20180930preview.go
- pkg/api/converterfromv20180930preview_test.go
- pkg/api/convertertoadmin.go
- pkg/api/convertertov20180930preview.go
- pkg/api/types.go
- pkg/api/validate.go
- pkg/api/validate_test.go
> make PeerVnetID a pointer in the internal model again

- docs/e2e/requirements.md
- test/e2e/specs/fakerp/etcdrecovery.go
Follow-up to https://github.com/openshift/openshift-azure/pull/999
> Remove etcd restore e2e test requirement

- cmd/createorupdate/createorupdate.go
- pkg/util/azureclient/openshiftmanagedcluster/2018-09-30-preview/client.go
- pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
- test/clients/azure/client.go
Fixes https://github.com/openshift/openshift-azure/issues/980
> Move OSA clients out of pkg/api

- pkg/arm/resources_test.go
> Add unittests for fixupDepends

- pkg/fakerp/server.go
> Update location headers set in fakerp delete handler

- hack/create.sh
- hack/delete.sh
- hack/e2e.sh
- hack/etcdrecovery.sh
- hack/upgrade.sh
> Remove reliance on lsof

- hack/create.sh
- hack/delete.sh
- hack/e2e.sh
- hack/etcdrecovery.sh
- hack/upgrade.sh
This reverts commit f07fb7bae80010571625283343dbc057a6ad86a3.
> Revert "Remove reliance on lsof"

- cmd/createorupdate/createorupdate.go
- cmd/sync/sync.go
- pkg/api/plugin.go
- pkg/cluster/types.go
- pkg/fakerp/config.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/server.go
- pkg/util/azureclient/azureclient.go
- pkg/util/azureclient/compute.go
- pkg/util/azureclient/graphrbac.go
- pkg/util/azureclient/managedapplications.go
- pkg/util/azureclient/marketplaceordering.go
- pkg/util/azureclient/network.go
- pkg/util/azureclient/resources.go
- pkg/util/azureclient/storage.go
- pkg/util/configblob/container.go
- test/clients/azure/client.go
This further cleans PluginConfig and moves accept languages field into context object
> move AcceptLanguage to context

- pkg/fakerp/restore.go
- pkg/fakerp/rotatesecrets.go
- pkg/fakerp/server.go
closes #1049 
/cc @mjudeikis @kargakis @jim-minter
> Refactor fakerp http handlers

- docs/ci_babysitting.md
Moving this over from Jira. I am going to link this back to Jira once merged.
/cc @Makdaam @jim-minter
> Add CI babysitting doc

- hack/etcdrecovery.sh
- hack/upgrade.sh
> remove timeout flag

- OWNERS
/cc @mjudeikis @charlesakalugwu
> Remove kargakis from OWNERS

- pkg/config/derive.go
- pkg/config/derive_test.go
- pkg/util/cloudprovider/cloudprovider.go
> fix for ILB

- Makefile
Adding an extra `$` to make variables work in Makefile.
> Fix var interpolation inside of awk statement

- Makefile
@charlesakalugwu please lgtm this
> change rg format

- pluginconfig/pluginconfig-311.yaml
> release 3.11.51

- pluginconfig/pluginconfig-311.yaml
@charlesakalugwu @Makdaam please lgtm
> update plugin config for v1 release

- cmd/sync/sync.go
- hack/update-addons/update-addons.go
- pkg/addons/addons.go
- pkg/addons/client.go
- pkg/addons/wants.go
Delete objects marked owned by the sync pod that do not show in the blueprint (config blob).
> Delete stray objects in sync pod

- pkg/api/plugin.go
- pkg/fakerp/config.go
- pkg/util/azureclient/azureclient.go
> remove context keys that are no longer used

- pkg/cluster/healthcheck.go
> re-enable the admin console healthcheck

- pkg/api/plugin.go
follow-up to #1133 
/cc @jim-minter @mjudeikis @Makdaam @kwoodson
> Add geneva actions interface

- pluginconfig/pluginconfig-311.yaml
Update pluginConfig for release v2.0
/cc @openshift/sig-azure 
/hold 
this needs to go first: https://github.com/openshift/release/pull/2872
> OSA release v2.0 upgrade

- pkg/util/ready/ready.go
- test/e2e/standard/cluster.go
- test/e2e/standard/sanitychecker.go
Add ELB and ILB test
fixes: https://github.com/openshift/openshift-azure/issues/1111
> Add ILB and ELB tests

- docs/testing.md
Update test commands for reference
> update test doc

- pluginconfig/pluginconfig-311.yaml
@asalkeld if this passes e2e please lgtm it
@y-cote fyi
related to #1177
> bump ose-cluster-monitoring-operator to v3.11.82

- pluginconfig/pluginconfig-311.yaml
> Release v2.2

- hack/codecov-report.sh
> Specify prow variables to codecov scripts

- pluginconfig/pluginconfig-311.yaml
> stop using td-agent:latest

- hack/aad.sh
- pkg/controllers/customeradmin/group_mapping.go
- pkg/controllers/customeradmin/group_reconcile.go
follow-up for e2e at https://github.com/openshift/openshift-azure/issues/1222
> fix group-sync

- pkg/api/plugin.go
- pkg/cluster/etcdrestore.go
- pkg/cluster/types.go
- pkg/fakerp/admin_handlers.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- pkg/util/mocks/mock_cluster/types.go
closes #1228
```release-note
NONE
```
> Check for etcd backup blob in the plugin, not the fakerp

- pkg/fakerp/customer_handlers.go
closes #1227 
```release-note
NONE
```
> Move client creates into one place for the delete

- cmd/metricsbridge/metricsbridge.go
Reverts openshift/openshift-azure#1235
```release-note
NONE
```
> Revert "metricsbridge - adding an option to calculate rate of a metric"

- pkg/arm/resources.go
remove tcp reset to make sure we test what we deploy
```release-note
NONE
```
> remove TCP Reset

- README.md
- pkg/api/validate/validate_test.go
- pkg/api/validate/validators.go
fixes: https://github.com/openshift/openshift-azure/issues/253
/cc @patrickstrick
```release-note
MSFT: increase infra node count to 3. Important: CLI needs to be updated to reflect this.
```
> increase infra node count 3

- test/e2e/specs/customer_admin.go
```
• Failure [6.981 seconds]
Openshift on Azure customer-admin e2e tests [CustomerAdmin][Fake]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/customer_admin.go:22
should be able to manage Quotas, LimitRanges, and EgressNetworkPolicies [It]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/customer_admin.go:110
Expected error:
<*errors.StatusError | 0xc00078e3f0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
Status: "Failure",
Message: "resourcequotas is forbidden: User \"customer-cluster-admin\" cannot create resourcequotas in the namespace \"e2e-test-xrsbq\": no RBAC policy matched",
Reason: "Forbidden",
Details: {
Name: "",
Group: "",
Kind: "resourcequotas",
UID: "",
Causes: nil, …
```
> fix quota flake due to azure-controller not having created rolebinding yet

- cmd/metricsbridge/metricsbridge.go
- pkg/config/names.go
- pkg/config/names_test.go
both values are derived from the IP address in "instance".
```release-note
NONE
```
> Adding two new dimensions in metrics-bridge: hostname and agentRole

- test/e2e/specs/customer_admin.go
This pull request adds a test for aad sync.
Relies on https://github.com/openshift/release/pull/3022
Fixes https://github.com/openshift/openshift-azure/issues/1222
```release-note
None
```
> Adding customer admin sync test.

- pkg/api/plugin.go
- pkg/cluster/admin_actions.go
- pkg/cluster/types.go
- pkg/fakerp/admin_handlers.go
- pkg/fakerp/routes.go
- pkg/plugin/plugin.go
- pkg/util/azureclient/compute_addons.go
- pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
- pkg/util/azureclient/resources.go
- pkg/util/mocks/mock_azureclient/azureclient.go
- pkg/util/mocks/mock_cluster/types.go
- test/e2e/specs/fakerp/command.go
```release-note
MSFT: provides run command geneva action for kubelet and networkmanager restart
```
Docker restart not working properly so not added - follow up in #1256
> run command geneva action

- Makefile
- pkg/api/2018-09-30-preview/api/types.go
- pkg/api/2018-09-30-preview/api/types_test.go
- pkg/api/admin/api/config.go
- pkg/api/admin/api/types.go
- pkg/api/admin/api/types_test.go
- pkg/api/config.go
- pkg/api/converterfromadmin.go
- pkg/api/converterfromplugin.go
- pkg/api/converterfromplugin_test.go
- pkg/api/converterfromv20180930preview.go
- pkg/api/converterfromv20180930preview_test.go
- pkg/api/convertertoadmin.go
- pkg/api/convertertov20180930preview.go
- pkg/api/plugin/api/config.go
- pkg/api/types.go
- pkg/api/types_test.go
- pkg/api/validate/plugin.go
- pkg/api/validate/plugin_test.go
- pkg/api/validate/types.go
- pkg/api/validate/types_test.go
- pluginconfig/pluginconfig-311.yaml
- test/e2e/specs/fakerp/admin_api.go
```release-note
MSFT: renames existing Config.ClusterVersion -> Config.PluginVersion; adds additional Properties.ClusterVersion field
```
@mjudeikis ptal
> Rename ClusterVersion -> PluginVersion, add ClusterVersion

- .gitignore
- Makefile
- images/e2e-tests/Dockerfile
reraising so I can have access to CI!  :/
```release-notes
NONE
```
> Simple makefile improvements

- pluginconfig/pluginconfig-311.yaml
```release-notes
311.82.20190311 Image release
```
> update to 311.82.20190311

- pkg/api/validate/plugin.go
/cc @jim-minter 
https://bugzilla.redhat.com/show_bug.cgi?id=1689366 
```release-notes
NONE
```
> logging level validation fix

- pkg/addons/translate.go
fixes: https://github.com/openshift/openshift-azure/issues/1295 
```release-notes
NONE
```
> tlsproxy fix

- Makefile
- hack/ci-operator-prepare.sh
- hack/delete.sh
- hack/upgrade-e2e.sh
- hack/vmimage.sh
> Improve CI operator integrations

- RELEASE_NOTES.md
- pluginconfig/pluginconfig-311.yaml
> Release v3.0

- test/e2e/standard/cluster.go
> check ksm in e2e

- pkg/fakerp/fakerp.go
Moves config writer before creation.
fixes: https://github.com/openshift/openshift-azure/issues/1308
```release-note
NONE
```
> move helpers persistence before creation

- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
```release-note
prevent update from succeeding unless cluster version matches plugin version
```
> prevent update from succeeding unless cluster version matches plugin version

- RELEASE_NOTES.md
- pkg/arm/arm.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- pluginconfig/pluginconfig-311.yaml
> release v3.1

- docs/release.md
This adds the release CHANGELOG.md creation steps.
```release-note
NONE
```
> Update release docs to include CHANGELOG.md.

- pkg/api/plugin.go
- pkg/cluster/kubeclient/ready.go
- pkg/plugin/plugin.go
```release-note
NONE
```
fixes #1325
> handle service unavailable condition before pod has even started

- Makefile
- cmd/createorupdate/createorupdate.go
- pkg/cluster/hash.go
- pkg/cluster/hash_test.go
- pkg/fakerp/client/manifest.go
- test/e2e/specs/fakerp/admin.go
- test/e2e/specs/fakerp/admin_api.go
- test/e2e/specs/fakerp/forceupdate.go
- test/e2e/specs/realrp/vnetpeering.go
- test/e2e/specs/scaleupdown.go
```release-note
Fix an issue which was causing node rotations on scale; hardened testing
```
> make hash invariant of SAS URIs

- Makefile
- RELEASE_NOTES.md
- pkg/cluster/hash.go
- pkg/cluster/hash_test.go
- pluginconfig/pluginconfig-311.yaml
- test/e2e/specs/scaleupdown.go
```release-note
NONE
```
backport of #1329
> Release v3.2

- pkg/cluster/updateblob/updateblob_test.go
Apparently reading a malformed blob does not return an error. May need to use [encoding/json/#Decoder.DisallowUnknownFields](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields) to catch those cases.
```release-note
NONE
```
> Blob read unit tests

- pluginconfig/pluginconfig-311.yaml
```release-note
update OpenShift to 3.11.88
```
> update to 311.88.20190322

- hack/tests/create-e2e.sh
- hack/tests/upgrade-e2e.sh
> label resource groups more clearly

- hack/artifacts.sh
- hack/tests/e2e-create.sh
- hack/tests/e2e-upgrade.sh
- hack/vmimage.sh
> always call az group delete at end of CI run (extra protection)

- hack/tests/e2e-upgrade.sh
- pkg/arm/v4/resources.go
- pkg/cluster/initialize.go
```release-note
NONE
```
@charlesakalugwu one of the recommendations mentioned - the others are in AZURE-312 and are less urgent IMO
> require https traffic to storage accounts

- hack/tests/ci-operator-prepare.sh
- hack/tests/e2e-upgrade.sh
```release-note
NONE
```
We need to provide config so we can construct a route for canary application.
> scriptfix - provide config file config

- cmd/sync/sync.go
- pkg/arm/v3/arm.go
- pkg/cluster/hash.go
- pkg/cluster/hash_test.go
- pkg/startup/v3/startup.go
- pkg/sync/sync.go
- pkg/sync/v3/sync.go
- pkg/sync/v4/sync.go
- test/util/populate/dummycerts.go
```release-note
NONE
```
this adds testing to make sure our hashes don't change over time, causing cluster rotations
> hash stability tests

- cmd/startup/startup.go
- pkg/api/plugin.go
- pkg/arm/v3/arm.go
- pkg/arm/v4/arm.go
- pkg/cluster/hash.go
- pkg/fakerp/config.go
- pkg/startup/startup.go
- pkg/startup/v3/startup.go
- pkg/startup/v4/startup.go
> add code to allow debugging of hash functions

- cmd/monitoring/monitoring.go
Monitoring opens a lot of short-lived TCP connections to the LB IP and to
backend IPs simultaneously.  Note the following:
1. Linux allows reuse of local TCP source ports as long as the remote IP/port
tuples are unique across the local IP/port tuple.
2. Azure external LBs work by NATing, not by proxying.  The LB backend always
sees the client IP/port tuple unchanged.
The `LocalAddr` setting below, which is essential, causes bind("0.0.0.0:0") to
be called before connect() for each new monitoring connection.  This guarantees
that the local source port for the monitoring connection in question is unique
across all connections on the local system.
If bind() is not called here, it is possible for a local->backend monitoring
connection and a local->LB connection, perhaps in the fake RP or in a …
> Fix networking flake caused by exuberant monitoring

- cmd/monitoring/monitoring.go
- hack/artifacts.sh
- hack/monitoring.sh
- hack/tests/ci-operator-prepare.sh
- hack/tests/e2e-create.sh
- hack/tests/e2e-upgrade.sh
- hack/vmimage.sh
- pkg/cluster/hash_test.go
- pkg/startup/v4/bindata.go
- pkg/startup/v4/data/master/etc/origin/master/admin.crt
- pkg/startup/v4/data/master/etc/origin/master/admin.key
- pkg/util/blackbox/types.go
> fetch kubelet goroutines to artifacts

- hack/tests/ci-operator-prepare.sh
- hack/tests/e2e-scale-on-lower-version.sh
closes #1358
```release-note
NONE
```
> Scale v3 on v4 plugin test

- test/e2e/standard/cluster.go
relates to #1336 
This is somewhat speculative.. see the issue
```release-notes
NONE
```
> wait for each lb to be ready before creating the next

- hack/tests/e2e-scale-previous.sh
> rebase fixes to hack/tests/e2e-scale-on-lower-version.sh and rename

- cmd/monitoring/monitoring.go
```release-note
NONE
```
Make route loading blocking. The config file is being persisted much later than arm template.
> canary app metrics

- pkg/plugin/plugin.go
```release-note
make TestConfig optional in NewPlugin
```
> make TestConfig optional in NewPlugin

- test/e2e/standard/cluster.go
Reverts openshift/openshift-azure#1386
```release-note
NONE
```
> Revert "wait for each lb to be ready before creating the next"

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> release v4.0

- Makefile
> fix makefile tagging

- test/e2e/standard/testapps.go
> fix flake caused by app crashlooping while database goes away

- docs/release.md
- pluginconfig/pluginconfig-311.yaml
> fix minor issue in pluginconfig

- pluginconfig/pluginconfig-311.yaml
- test/e2e/standard/sanitychecker.go
> increase debugging to understand ongoing storage issue

- pkg/api/plugin.go
- pkg/cluster/kubeclient/roundtrip.go
- pkg/fakerp/admin_handlers.go
- pkg/fakerp/config.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/ssh.go
```release-note
NONE
```
when arm deploy failures occur, try to ssh to the affected nodes to capture logs
> more arm failure logging

- OWNERS
> Add myself to the OWNERS file

- README.md
- env.example
- pkg/fakerp/fakerp.go
> Update README and env.example

- hack/validate-imports/validate-imports.go
- pkg/api/plugin.go
- pkg/api/types.go
- pkg/cluster/etcdrestore.go
- pkg/cluster/types.go
- pkg/fakerp/admin_handlers.go
- pkg/fakerp/routes.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
- pkg/util/mocks/mock_cluster/types.go
- test/e2e/specs/fakerp/etcdrecovery.go
```release-note
* add geneva action to list backup blobs
```
> add geneva action to list backup blobs

- cmd/monitoring/monitoring.go
```release-note
NONE
```
fixes #1435 
@charlesakalugwu
> re-add nil check which I should not have removed

- pkg/fakerp/fakerp.go
- pkg/startup/v3/derive.go
- pkg/startup/v4/derive.go
- pkg/startup/v5/derive.go
- pkg/util/cloudprovider/cloudprovider.go
- pkg/util/cloudprovider/cloudprovider_test.go
- pkg/util/derived/derived.go
- pkg/util/derived/derived_test.go
```release-note
NONE
```
should significantly reduce Azure API calls and increase reliability
> switch on UseInstanceMetadata

- cmd/createorupdate/createorupdate.go
- hack/setup-rbac/main.go
- pkg/fakerp/client/config.go
- pkg/fakerp/client/groups.go
- pkg/fakerp/client/manifest.go
- test/e2e/specs/realrp/realrp.go
- test/e2e/specs/realrp/vnetpeering.go
- test/manifests/fakerp/create.yaml
- test/manifests/realrp/create.yaml
```release-note
NONE
```
@mjudeikis once this merges should be able to set REGION=eastus,westeurope,northeurope in the CI secret.  We have quota on northeurope and the VMSS fix is rolled out there - ptal.
> Prepare for northeurope

- OWNERS
> Added grant to owners file

- Makefile
- hack/vmimage.sh
> fix tags in Makefile

- CHANGELOG.md
- pkg/api/validate/plugin.go
- pkg/fakerp/server.go
> validate canary image empty on v3.2

- pkg/fakerp/fakerp.go
```release-note
NONE
```
fixes #1442
> fix ssh: rejected: administratively prohibited (open failed) error

- README.md
> add note about jq to readme

- pkg/util/ready/ready.go
- test/clients/openshift/client.go
- test/clients/openshift/login.go
- test/clients/openshift/template.go
- test/e2e/specs/osba_app.go
- test/manifests/osba/osba-os-template.yaml
Add a complete e2e test for the selection and validation of an app selected from the OSBA.
```release-note
NONE
```
> Provide an E2E test for the OSBA.

- pkg/fakerp/fakerp.go
> add missing hyphen

- pkg/fakerp/fakerp.go
- pkg/startup/v3/derive.go
- pkg/startup/v4/derive.go
- pkg/startup/v5/derive.go
- pkg/util/cloudprovider/cloudprovider.go
- pkg/util/cloudprovider/cloudprovider_test.go
- pkg/util/derived/derived.go
- pkg/util/derived/derived_test.go
```release-note
Enable cloud API rate limiting for nodes
```
Closes #1480.
> Enable cloud API rate limiting for nodes

- pluginconfig/pluginconfig-311.yaml
```release-note
bump to OpenShift 3.11.98
```
> bump v5 to 3.11.98

- pkg/entrypoint/metricsbridge/metrics-bridge-example-config.yaml
> Forgot to reflect current config

- pkg/controllers/customeradmin/group_mapping.go
- pkg/controllers/customeradmin/group_mapping_test.go
```release-note
NONE
```
fixes #1498
> fix NPE in customeradmin

- README.md
```release-note
NONE
```
Closes #627.
> Add disclaimer to README for non aos-azure team members

- test/clients/openshift/dumpinfo.go
relates #1481
```release-note
NONE
```
> add build logs to e2e DumpInfo

- pkg/api/validate/validators.go
```release-note
Increase maximum node count to 30
```
> increase maximum nodes to 30

- pkg/fakerp/fakerp.go
- pkg/util/azureclient/compute.go
- pkg/util/azureclient/resources.go
> increase scaleset timeout to 30 minutes

- test/e2e/standard/cluster.go
relates #1515
```release-note
NONE
```
> Increase the timeout for the redis redhat.io deployment

- pkg/fakerp/aad.go
> retry on NoBackingApplicationObject error

- pkg/cluster/kubeclient/ready.go
- pkg/plugin/integration_test.go
```release-note
NONE
```
We hit a race[1] where we checked the pod's view of readiness before the controller had acted on a change in goal state (should have been checking ObservedGeneration)
[1] https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1531/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/189/build-log.txt
@asalkeld @mjudeikis @ehashman fyi
> Check for sync pod readiness correctly

- test/e2e/specs/customer_admin.go
```release-note
NONE
```
fixes #1498
> fix customeradmin test

- test/e2e/specs/osba_app.go
> Add DumpInfo to help with Flake debugging.

- test/e2e/standard/cluster.go
> increase redis deploy timeout to 20 minutes

- hack/setup-rbac/main.go
- hack/vmimage.sh
- pkg/fakerp/aad.go
- pkg/fakerp/customer_handlers.go
- pkg/fakerp/fakerp.go
```release-note
NONE
```
fixes #1545 
@mjudeikis fyi
> fix image building rbac error

- test/e2e/specs/fakerp/prometheus.go
```release-note
NONE
```
fixes: #1201
> Adding kube-controllers to e2e fakerp prometheus

- docs/e2e/appinsights.md
```release-note
NONE
```
Minor queries updates
> queries and links

- pkg/api/plugin.go
- pkg/plugin/plugin.go
- test/e2e/specs/fakerp/command.go
```release-note
Adding run command to restart docker
```
Fixes: #1256
> Adding geneva command to restart docker and tests

- hack/tests/e2e-scaleupdown-previous.sh
- hack/tests/e2e-upgrade.sh
```release-note
NONE
```
fixes #1582
> work around broken v3.2 build

- cmd/createorupdate/createorupdate.go
- pkg/cluster/initialize.go
- pkg/cluster/kubeclient/ready.go
- pkg/util/azureclient/storage/storage.go
- pkg/util/configblob/container.go
- pkg/util/errors/errors.go
- pkg/util/errors/errors_test.go
- pkg/util/wait/wait.go
there is some inconsistent error handling for network errors, let's fix this up.
closes #1400
```release-note
NONE
```
> retry when we get network errors

- pkg/util/random/random.go
> try not to use microsoft reserved names

- pkg/cluster/scaler/scaler.go
- pkg/cluster/update_worker.go
- pkg/cluster/update_worker_test.go
- pkg/util/azureclient/compute/virtualmachinescalesets.go
- pkg/util/azureclient/fake/compute/virtualmachinescalesets.go
- pkg/util/mocks/mock_azureclient/mock_compute/compute.go
- pkg/util/mocks/mock_scaler/scaler.go
> add debugging on scale failure

- hack/periodic/content-update.sh
```release-note
NONE
```
Content PR's being created with "invalid" content due to missing generate step
> add generate to content update script

- pkg/util/azureclient/retry.go
- pkg/util/errors/errors.go
- pkg/util/errors/errors_test.go
closes #1592
```release-note
NONE
```
> Retry Azure "GET" requests on connection reset by peer

- pkg/cluster/scaler/scaler.go
> remove scale logging

- test/manifests/fakerp/create.yaml
```release-note
NONE
```
This is the last TODO on the defaulting issue. Closes #336.
> Simplify create config by removing default values

- pkg/util/errors/errors.go
- pkg/util/errors/errors_test.go
```release-note
NONE
```
closes #1400
> Unwrap "net/http: HTTP/1.x transport connection broken" error

- pkg/plugin/integration_test.go
- pkg/util/azureclient/fake/cloud.go
- pkg/util/azureclient/fake/compute/virtualmachinescalesets.go
- pkg/util/azureclient/fake/compute/virtualmachinescalesetvms.go
- pkg/util/azureclient/fake/keyvault/keyvault.go
- pkg/util/azureclient/fake/storage/accounts.go
- pkg/util/azureclient/fake/storage/blob.go
```release-note
NONE
```
Start adding more integration tests to get confidence in what causes node rotations.
/cc @jim-minter 
It helps to review commit by commit.
> Add more integration tests

- CHANGELOG.md
- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/fakerp/client/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Security release for Microarchitectural Data Sampling (MDS)
```
> release 20190514 Security fix

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/fakerp/client/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Prepare for release v4.4, v5.1
Add new VM image with security updates 
```
Adds Required changes for 4.4 and 5.1 release to the master
> Release prep (4.4, 5.1)

- hack/periodic/content-update.sh
- hack/tests/ci-prepare.sh
- hack/tests/codecov.sh
- hack/tests/create.sh
- hack/tests/e2e-prod.sh
- hack/tests/e2e-scaleupdown-previous.sh
- hack/tests/e2e-upgrade.sh
- hack/vmimage.sh
```release-note
NONE
```
Trying to get rid of ci-operator, this is groundwork for removing ci-operator in the release repo
> groundwork for removing ci-operator

- pkg/sync/v6/client.go
```release-note
NONE
```
/cc @mjudeikis 
fixes #1288
> non-updateable objects are deleted and re-created

- OWNERS
> Add Angus to the approvers list

- pkg/entrypoint/sync/sync.go
This adds 5 new metrics for the sync process
- sync_info (gauge) with labels
- plugin_version
- image
- period_seconds
- sync_errors_total (counter)
- sync_executions_inflight (gauge)
- sync_last_executed (gauge)
- sync_duration_seconds (summary)
/cc @jim-minter @kwoodson @Makdaam @ehashman 
```release-note
NONE
```
> Add prometheus instrumentation to sync

- cmd/azure/azure.go
```release-note
NONE
```
/cc @mjudeikis
> Add remaining install config entries

- .gitignore
- cmd/azure/azure.go
- hack/create.sh
> Openshift v4 export OPENSHIFT_INSTALL_DATA

- cmd/azure/azure.go
> Initialise the plugins

- OWNERS
```release-note
NONE
```
/assign @jim-minter
> Add myself as an approver

- hack/e2e.sh
- pkg/sync/v6/sync.go
This adds race detection to our unit and e2e tests
/cc @jim-minter @grantomation @Makdaam 
```release-note
NONE
```
> Add race detection to e2e tests

- vendor/github.com/openshift/installer/pkg/asset/machines/azure/machines.go
- vendor/github.com/openshift/installer/pkg/destroy/azure/azure.go
> Openshift v4

- CHANGELOG.md
- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Bumping release to v5.2.
> Release v5.2

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
Bumping image version to 311.104.20190617
```release-note
None
```
> Bumping image version to 311.104.20190617

- pkg/entrypoint/sync/sync.go
This adds a separate Prometheus registry for the sync process and therefore prevents sync metrics from spilling over into metrics for other parts of the plugin cli. 
```release-note
NONE
```
This is a pre-requisite to unholding #1722.
In a follow-up we'll come up with a design which centralizes the registry, conditionally registers metrics from different parts of the cli into the registry and allows for testability of the instrumentation. 
/cc @Makdaam @mjudeikis
> Use separate prometheus registry for sync metrics

- test/manifests/realrp/create.yaml
This reverts commit 42a894b120140fcea4e10af8d4e2287676277e93.
```release-note
NONE
```
> Revert "Add default router profile to real rp sample manifest"

- Makefile
- pkg/api/plugin.go
> v4: Misc small fixes

- .gitignore
> gitignore: add the testinsights binary to the list

- hack/tests/origin-conformance.sh
> Entrypoint for conformance test

- OWNERS
> Adds m1kola as a reviewer

- pkg/controllers/customeradmin/group_mapping.go
- pkg/controllers/customeradmin/group_mapping_test.go
- pkg/controllers/customeradmin/group_reconcile.go
```release-notes
fix group sync for guest accounts
```
Fix group sync for guest accounts
> group sync fix to include external users

- README.md
> Add a note on GNU utils for macOS

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
Create release v6.0 with updated pluginconfig and changelog
```release-note
NONE
```
**Image Name for v6.0 release**: rhel7-3.11-201907191212
**Disk version**: 311.117.20190719
> Create release v6.0 with pluginconfig and changelog

- hack/periodic/content-update.sh
> add \r to content-update script, think it's needed for the release note tooling

- cmd/azureblobupload/azureblobupload.go
- cmd/azureblobupload/codecov_dummy_test.go
- cmd/vhdfooter/codecov_dummy_test.go
- cmd/vhdfooter/vhdfooter.go
> Moving the vhd-footer and azureblobupload to upstream repo

- OWNERS
```release-note
none
```
-  Add troy0820 to OWNERS file
> Add troy0820 to OWNERS file

- cmd/monitoring/monitoring.go
- cmd/releasenotes/releasenotes.go
- pkg/fakerp/fakerp.go
- pkg/fakerp/store/store.go
- pkg/vmimage/ssh.go
- test/clients/openshift/dumpinfo.go
- test/e2e/specs/fakerp/metricsbridge.go
- test/e2e/specs/fakerp/prometheus.go
```release-note
NONE
```
This PR should fix/whitelist all issues found by gosec so that #1820 can go ahead.
Work in progress (there will be more commits).
> Fixing issues found by gosec

- pkg/arm/v7/arm.go
- pkg/cluster/hash.go
- pkg/plugin/integration_test.go
- pkg/startup/v7/startup.go
```release-note
NONE
```
@thekad ptal
> minor fixes found while debugging hash changes

- README.md
- hack/aad.sh
```release-note
NONE
```
Rename shared secret
> rename secret 

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Add changelog, pin container images to release tag.
> Prepare v7.0 release

- docs/release.md
```release-note
NONE
```
Updating the documentation on doing a release to better reflect the process I just went through.
/cc @mjudeikis @kwoodson
> Update release process documentation

- pkg/entrypoint/tlsproxy/tlsproxy.go
```release-note
NONE
```
TLSProxy changes to enable usage for vmimage
> fix tlsproxy

- test/e2e/specs/fakerp/loglevel.go
- test/e2e/specs/fakerp/setcontainerimage.go
part of Jira-221
```release-note
NONE
```
> Add some assertions to prove update reentrancy

- pkg/sync/v8/sync.go
The sync pod logs have the following errors:
```
Unsolicited response received on idle HTTP channel starting with \"HTTP/1.0 408 Request Time-ou
Cache-Control: no-cache
Connection: close
```
According to https://giedrius.blog/2018/10/25/gos-http-transport-and-408-response-code-whats-the-relationship/ this is because of our keepAlives. Our RoundTripper disables keepAlives and instead
makes new connections and retries. So this seems like a good idea to use the same RoundTripper for our sync pod kubeclient. 
```release-note
NONE
```
closes #1710
> Use RoundTripper in the sync pod

- pkg/util/errors/errors.go
```release-note
NONE
```
Just a follow up on a merged PR.
> remove unused netHTTPErrorPrefixLen

- cmd/createorupdate/createorupdate.go
- hack/create.sh
- hack/delete.sh
- hack/e2e.sh
- hack/etcdrecovery.sh
- hack/upgrade.sh
- pkg/fakerp/client/groups.go
- pkg/util/azureclient/resources/groups.go
- pkg/util/mocks/mock_azureclient/mock_resources/resources.go
```release-note
NONE
```
relates to #1617
> Fix fakerp "trap" and used azureclient.resources.Group

- hack/delete.sh
```release-note
NONE
```
just a small syntax error fix
> fixing small syntax error in hack/delete.sh

- hack/ci-notify/codecov_dummy_test.go
- hack/ci-notify/main.go
- hack/vmimage.sh
Adding ci notifications to vmbuild.
```release-note:
None
```
> Add ci-notify to vmimage build.

- hack/vmimage.sh
Fixing quoting issue with recent ci-notifications.
```release-note:
None
```
> Fix vmimage build quotes.

- pkg/cluster/hash_test.go
- pluginconfig/pluginconfig-311.yaml
> Fix pluginconfig.pluginVersion -> v9

- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
This is a cherry-pick of cbfb63eb524adf70c4f7cb57dfa8ed85432595b1 plus an update to the v9 VM image version.
> Update image versions in plugin config for v8/v9

- pkg/startup/v9/startup.go
- pkg/startup/v9/startup_test.go
This also fixes a bug where all common files were not getting written.
```release-note
NONE
```
/cc @mjudeikis
> Clean up startup.writeFiles() and add tests

- pkg/api/plugin.go
> remove unused PluginStepEnrichMonitorProfile

- pkg/controllers/customeradmin/group_mapping.go
- pkg/controllers/customeradmin/group_mapping_test.go
- pkg/util/mail/codecov_dummy_test.go
- pkg/util/mail/mail.go
- pkg/util/mail/mail_test.go
```release-note
NONE
```
Make group sync more robust
> make group mapping more robust

- pkg/fakerp/client/groups.go
```release-note
NONE
```
fixes #1628 #1617
> Fix fakerp ensure resource group flake

- test/e2e/specs/customer_admin.go
This PR adds an end to end test to validate that members of the `osa-customer-admins` group are able to get and update the prometheus data collection config of the log analytics agent. In addition, it validates that members of `osa-customer-admins` group are unable to access other configmaps utilized by the log analytics agent. 
```release-note
NONE
```
/cc @asalkeld @ehashman
> Verify that customer-admins can update the azure monitor agents' prometheus config

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> release v9.0

- hack/upgrade.sh
```release-note
NONE
```
@asalkeld ptal
> correct warning message

- OWNERS
> remove y-cote and pweil- from OWNERS

- pluginconfig/pluginconfig-311.yaml
```release-note
Update to [OpenShift 3.11.146](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-146)
```
> Update upstream versions

- hack/periodic/content-update.sh
> fix content script

- pkg/cluster/scaler/scaler.go
- pkg/cluster/update_worker.go
- pkg/cluster/update_worker_test.go
- pkg/fakerp/fakerp.go
- pkg/util/mocks/mock_scaler/scaler.go
- test/e2e/specs/fakerp/securityupdates.go
- test/util/diagnostics/codecov_dummy_test.go
- test/util/diagnostics/scaleset.go
- test/util/diagnostics/ssh.go
- test/util/log/codecov_dummy_test.go
- test/util/populate/codecov_dummy_test.go
So that we can reuse both diagnostics from fakerp and scaler
```release-note
NONE
```
> move diagnostics to test/util/diagnostics

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> Release v10 images and changelog

- pluginconfig/pluginconfig-311.yaml
[AZURE-470](https://jira.coreos.com/browse/AZURE-470)
```release-note
NONE
```
> Updates VM image for v11

- OWNERS
> Add olga as a reviewer

- env.example
- pkg/api/2019-10-27-preview/converterfrominternal.go
- pkg/api/2019-10-27-preview/convertertointernal.go
- pkg/api/2019-10-27-preview/types.go
- pkg/api/2019-10-27-preview/types_test.go
- pkg/api/mock.go
- pkg/api/types.go
- pkg/api/types_test.go
- pkg/fakerp/client/config.go
- test/manifests/fakerp/create.yaml
```release-note
Add PrivateAPIServer field to MasterPoolProfile 
```
> Add PrivateAPIServer to the public API

- CHANGELOG.md
- Makefile
- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
> Release v10.1

- pkg/fakerp/proxy.go
```release-note
NONE
```
Just a slight de-duplication in code.
> Slight improvement to secret loading

- Makefile
- docs/commands.md
- docs/testing.md
- hack/generate-test-commands/codecov_dummy_test.go
- hack/generate-test-commands/commands.md
- hack/generate-test-commands/generate-test-commands.go
- hack/periodic/content-update.sh
```release-note
NONE
```
AutoGenerated test commands docs
> auto-generated docs

- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Final PR for the v10.1 release.
> Update container images for v10.1

- pkg/fakerp/fakerp.go
> don't set PrivateAPIServer on in v10 fakerp

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
/cc @ehashman
> Support upgrading from v10.1

- pkg/api/2019-10-27-preview/converterfrominternal.go
- pkg/api/2019-10-27-preview/convertertointernal.go
- pkg/api/2019-10-27-preview/types.go
- pkg/api/2019-10-27-preview/types_test.go
- test/manifests/fakerp/create.yaml
```release-note
Change the API for Private Cluster as per new agreed model
```
closes #2024 
/cc @ehashman 
@julienstroheker Hopefully this is what you are after.
> Change the API for Private Cluster as per new agreed model

- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
@ehashman @mjudeikis fyi
> use latest azure image from ci-azure:latest in pluginconfig

- hack/ci-notify/main.go
> condense OPENSHIFT_AZURE_ROBOT_TOKEN and GITHUB_TOKEN

- OWNERS
Add pnasrat to OWNERS 
```release-note
NONE
```
> Add pnasrat to openshift-azure OWNERS

- docs/release.md
> Fix link to VM image releasing SOP

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> Prepare for Release v11.0

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> v12.0 images and changelog

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Create v10.2 and new image
```
> Updating image version to 311.153.20191113 and create 10.2

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Updating image version to 311.153.20191113 and create 12.1
```
> Updating image version to 311.153.20191113 and create 12.1

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Updating to 311.153.20191113 and creating v10.2,v12.1
```
> Updating to 311.153.20191113 and creating v10.2,v12.1

- pkg/api/plugin.go
- pkg/cluster/admin_actions.go
- pkg/cluster/types.go
- pkg/fakerp/admin_handlers.go
- pkg/fakerp/routes.go
- pkg/plugin/plugin.go
- pkg/util/mocks/mock_cluster/types.go
> Restart a vm geneva action

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Updating image and OpenShift release to 3.11.154
```
> Updating image release with v12.2

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
Updating image and openshift version to 3.11.154
```
> Updating image for v12.2

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> V12.2 pluginconfig and changelog

- pkg/plugin/plugin_test.go
> Adding test for restart action

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> Prep v13 release

- docs/e2e/appinsights.md
> Update resource group and resource names in appinsights.md

- OWNERS
> remove label from OWNERS

- hack/setup-rbac/main.go
> setup-rbac typo

- pluginconfig/pluginconfig-311.yaml
> Update VM image version

- pkg/controllers/customeradmin/group_mapping.go
- pkg/controllers/customeradmin/group_mapping_test.go
```release-note
Fix guest user syncing with prefix and no Mail
```
/cc @grantomation  @mjudeikis
> Fix guest user syncing with prefix and no Mail

- pluginconfig/pluginconfig-311.yaml
Addresses #2130.
```release-note
NONE
```
> Update to new patched VM image

- pkg/controllers/customeradmin/group_mapping.go
- pkg/controllers/customeradmin/group_mapping_test.go
adding a different case for when Mail field is set but UserPrincipalName matches a cluster user
```release-note
Fix user syncing when Mail field is set, but UserPrincipalName matches the cluster username
```
> Fix group sync for UserPrincipalName match

- CHANGELOG.md
- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
> [release-v13] Prep for release 13.1

- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Update pluginconfig with the 13.1 docker image.
> [release-v13] Update release images to 13.1

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Backporting the v13.1 release stuff from release-v13 branch.
> Backport v13.1 changes to master

- pluginconfig/pluginconfig-311.yaml
```release-note
Update to OpenShift [3.11.157](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-157)
```
/hold
Waiting on image publication.
> Update VM image and containers to OpenShift 3.11.157

- OWNERS
```release-note
Adding my GitHub account name to OWNERS file
```
> add nilsanderselde to OWNERS

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Prep for v14 release.
Since we skipped the v13 release I included all the changenotes from that as well.
> [release-v14] Prepare v14 release

- test/e2e/standard/cluster.go
> Remove dead code in e2e tests

- pkg/api/validate/api.go
```release-note
Add client id for use in unit tests which disables roleLister
```
> add client id for use in unit tests which disables roleLister

- pkg/api/validate/api.go
- pkg/api/validate/api_test.go
- pkg/api/validate/validators_test.go
```release-note
Fix config validation
```
> Release v14.config.fix

- pluginconfig/pluginconfig-311.yaml
```release-note
Updating images to 14.1
```
> Updating v14.0 images to v14.1

- docs/commands.md
- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
> Preparing v14.1 release

- pkg/fakerp/util.go
- pkg/startup/v10/derive.go
- pkg/startup/v12/derive.go
- pkg/startup/v14/derive.go
- pkg/startup/v15/derive.go
- pkg/startup/v71/derive.go
- pkg/util/derived/derived.go
- pkg/util/derived/derived_test.go
```release-note
Change cloud-provider config rate limits 
```
> align cloud-config values

- OWNERS
> remove reviewers

- pluginconfig/pluginconfig-311.yaml
```release-note
Updating vmimage
```
> Updating v15 with latest image build.

- hack/setup-rbac/main.go
```release-note
Fix rbac for ILB
```
Fix: https://github.com/openshift/openshift-azure/issues/2200
> Fix ILB controller panic

- pkg/api/validate/validators.go
- pkg/api/validate/validators_test.go
This reverts commit bf0695ef9f5b4dd59d442b405da01f6613bc3731, reversing
changes made to f5fade170b01c0c649aaf490eb7ce541a2a7cb3d.
```release-note
NONE
```
> Revert "Merge pull request #2204 from mjudeikis/node.count"

- docs/ci.md
```release-note
NONE
```
Add notes for CI application need to know. Removal of tribal knowledge.
> Add Ci notes

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> Release v15.0

- pkg/entrypoint/etcdbackup/etcdbackup.go
> Would be nice to know when the etcdbackup finishes

- pkg/startup/v15/startup.go
- pkg/startup/v16/startup.go
```release-note
Include private api server property to the worker nodes
```
> Include private api server inside of worker properties.

- CHANGELOG.md
> Add missing changelog note for oc binary builds

- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Update VM image with some security patches. Should address #2195.
> Bump VM image version

- pkg/api/validate/serviceprincipal.go
```release-note
Bugfix: Retry on AAD propagation failures
```
Fixes #2211.
> Retry on AAD propagation failures

- docs/release.md
```release-note
NONE
```
Freshen up the release docs a bit. This clarifies the order of steps, adds a few that are missing, and adds a header for the section on starting the next dev version, making it linkable.
> Improve release instructions

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> [release-v16] Release v16.0

- pluginconfig/pluginconfig-311.yaml
```release-note
Update images to 14.2
```
> update image version

- installer/install_openshift.sh
> Adding cluster installer script

- pkg/sync/v16/client.go
- pkg/sync/v17/client.go
```release-note
Allow to recreate omsagent daemonset in sync pod
```
I've tested this manually on master branch:
1. Create dev-cluster `make create` (make sure `AZURE_WORKSPACE_ID` is set to valid resourceid)
2. Check sync pod logs.
3. Remove sync pod by scaling it to 0: `oc scale deployment --replicas=0 --namespace=kube-system sync`
4. Apply this patch to simulate the upgrade problem that we have now: https://github.com/openshift/openshift-azure/commit/83d79e744258d1af223c69d0a5290f2491415bd0
5. `make run-sync` and observe it crashes ==> this proves that problem is reproduced.
6. Apply this fix: https://github.com/openshift/openshift-azure/commit/ba4a620287707b4837d774988f22d3a7572887e9
7. Restore the cluster and reproduce the problem again - this time sync pod runs with no problem.
* …
> Allow omsagent daemonset recreation in sync pod

- CHANGELOG.md
- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
> [release-v16] changenotes and pluginconfig for 16.1

- pkg/arm/arm.go
- pkg/cluster/hash_test.go
- pkg/config/config.go
- pkg/startup/startup.go
- pkg/sync/sync.go
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Backporting v16.1 configs, etc. to master.
> Backport 16.1

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> [release-v17] Release v17.0 plugin

- OWNERS
> Add hawkowl to OWNERS

- OWNERS
As per @jim-minter in https://github.com/openshift/openshift-azure/pull/2304#issuecomment-645440036
```release-note
NONE
```
> Remove gburges and sjkingo from OWNERS

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Add changelog. Pin containers
> release v18

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> [release-v19] Release v19.0

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
```release-note
Release v20.0
```
> Release v20 plugin config

- pkg/api/validate/plugin.go
- pkg/api/validate/plugin_test.go
> Allow unsetting securityPatchPackages cert

- docs/release.md
> Update release readme with new changes

- Makefile
- pkg/util/mocks/mock_arm/arm.go
- pkg/util/mocks/mock_config/config.go
- pkg/util/mocks/mock_startup/startup.go
- pkg/util/mocks/mock_writers/writers.go
> Generate validate rollback

- docs/release.md
Add how-to generate using image
```release-note
NONE
```
> Update generate using image

- hack/tests/ci-prepare.sh
> Rollback xtrace

- pkg/api/validate/plugin.go
- pkg/util/mocks/mock_arm/arm.go
- pkg/util/mocks/mock_config/config.go
- pkg/util/mocks/mock_startup/startup.go
- pkg/util/mocks/mock_writers/writers.go
- pluginconfig/pluginconfig-311.yaml
> Update versions 

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
```release-note
NONE
```
Release v21 update plugin config
> Update images & change log

- pkg/config/v21/generate.go
> Backport cert flow to v21

- CHANGELOG.md
- pluginconfig/pluginconfig-311.yaml
> pluginconfig + changelog

- .gitignore
- Makefile
- README.md
- docs/e2e/requirements.md
- pkg/cluster/hash_test.go
- pkg/config/v21/generate.go
- pkg/config/v22/generate.go
- test/manifests/osba/osba-os-template.yaml
- vault-secrets.py
SDN certification rotation was missing
```release-note
Fixes cluster certificate rotation: SDN certificate also needs to be rotated.
```
> Cert rotation fix
