pkg/config/generate.go
pkg/helm/chart/templates/Deployment.apps/servicecatalog-api.yaml

Still need to test but I think we can fix the sc breakage for now with this
fixes https://github.com/jim-minter/azure-helm/issues/3 
/hold

Fix service catalog permissions

---

cmd/sync/sync.go
pkg/addons/addons.go
pkg/addons/printers.go

@jim-minter @pweil- adds dry run for addons. I don't feel strong on how outputing the resources works (stdout vs generating all files in a directory even though I guess we want to latter for convenience). I am going to merge this for now since I need it for debugging.

Enable dry-running addon sync

---

pkg/helm/chart/templates/Deployment.apps/sync.yaml
pkg/helm/chart/templates/Secret/admin-kubeconfig.yaml

@kargakis fyi - I think the sync pod fundamentally requires the admin.kubeconfig.

readding admin.kubeconfig secret to HCP

---

aks/create.sh
aks/tiller.yaml
create.sh
delete.sh
pkg/helm/chart/templates/Deployment.apps/bootstrap-autoapprover.yaml
pkg/helm/chart/templates/Deployment.apps/master-api.yaml
pkg/helm/chart/templates/Deployment.apps/master-controllers.yaml
pkg/helm/chart/templates/Deployment.apps/master-etcd.yaml
pkg/helm/chart/templates/Deployment.apps/servicecatalog-api.yaml
pkg/helm/chart/templates/Deployment.apps/sync.yaml
pkg/helm/chart/templates/Secret/admin-kubeconfig.yaml
pkg/helm/chart/templates/Secret/bootstrap-autoapprover-kubeconfig.yaml
pkg/helm/chart/templates/Secret/etc-etcd.yaml
pkg/helm/chart/templates/Secret/etc-origin-cloudprovider.yaml
pkg/helm/chart/templates/Secret/etc-origin-master.yaml
pkg/helm/chart/templates/Secret/servicecatalog-api-kubeconfig.yaml
pkg/helm/chart/templates/Secret/servicecatalog-api.yaml
pkg/helm/chart/templates/Secret/sync.yaml
pkg/helm/chart/templates/Secret/tunnel.yaml
upgrade.sh

* Install tiller into AKS cluster
* Use helm/tiller for HCP create/upgrade/delete
* Use checksums to auto-kick HCP pods when their configs change
(and always lay down secrets before deployments on upgrade)

Properly use helm for HCP pods

---

README.md
pkg/arm/data/azuredeploy.json

At this point in time, I loop over scaleset so it has less code but mode complex logic. And this partially enables multiple compute pools in api model. Are we fine proceeding this way or better stick with bigger file and simpler json logic.
If we go this way of the loop we might want to create a separate security group for each pool? Or we just stick with 2 (nsg-infra and ngs-compute)? I would create a new one for each poll.

add BYO vnet option

---

glide.lock
glide.yaml

@jim-minter this allows us to run `glide install` inside a container w/o needing to mount any ssh keys

Use https in git pullspec

---

pkg/addons/addons.go
pkg/addons/client.go
pkg/jsonpath/jsonpath.go

Add a hash in all workload controllers' pod template annotations to
enable restarts on configmap/secret updates. This generates the
annotations just fine, but I still need to:
The latter seems problematic: we either have to ignore managing
serving certs (bad), or manage them but swallow redeploying all 
services that use serving certs the second time the sync pod is
going to be kicked in a running cluster (less bad).
@jim-minter @mjudeikis @pweil- 
https://trello.com/c/HbAY1ZAZ/171-hcp-sync-pod-restarts

Kick workloads when config refs get updated

---

pkg/addons/clean.go
pkg/addons/client.go

@jim-minter @kargakis @kwoodson @pweil- 
All services object is immutable when updating due `clusterIP`.
Any service which needs updating will trigger an error with immutable field https://github.com/jim-minter/azure-helm/issues/103
`handleSpecialObjects` was introduced to handle cases like this.
If service gets updated we need to add clusterIP manually (L164) because DeepCopy does not copy this field. (so cleaning of the existing is just removing data we need)

fix for services

---

cmd/createorupdate/createorupdate.go
cmd/healthcheck/healthcheck.go
cmd/sync/sync.go
pkg/addons/addons.go
pkg/api/config.go
pkg/api/marshal.go
pkg/api/plugin.go
pkg/api/types.go
pkg/arm/arm.go
pkg/config/generate.go
pkg/config/upgrade.go
pkg/healthcheck/healthcheck.go
pkg/plugin/plugin.go
pkg/util/util.go

Moves the config.Config type to the internal API type.  Persists a copy of the internal model and changes commands that expected an existing cluster (ones that read the manifest AND config) to use the persisted model.
@openshift/sig-azure 
@amanohar

move config to internal type

---

cmd/createorupdate/createorupdate.go
cmd/healthcheck/healthcheck.go
pkg/addons/translate.go
pkg/arm/arm.go
pkg/config/upgrade.go
pkg/healthcheck/healthcheck.go
pkg/jsonpath/jsonpath.go
pkg/plugin/plugin.go

update plugin to use custom logger, switch add on pieces that were static back to panics (like MustCompile), left other add on statements using logrus but expectation is that it will run in the pod so no custom logger support is there.
~~Not done: passing logger down to static impl methods that the plugin calls (example below).  Right now no logging is done there but we should add that.  When we do we will either pass the logger in the method signature (yuck) or move them to interface (`Generator`, etc) implementations so they can have state like the plugin.  If everyone is good with what is here now I think I'd like to go ahead and take care of moving them to have the logger available now so we don't forget later.~~  Edit: did it
@kargakis @mjudeikis @amanohar
```
func (p *plugin) …
```

custom logger

---

pkg/config/generate.go

This modifies the base sku name since origin_ was removed by our automated tools.
I ran into this error until I updated:
```
msrest.http_logger : {"error":{"code":"MarketplacePurchaseEligibilityFailed","message":"Marketplace purchase eligibilty check returned errors. See inner errors for details. ","details":[{"code":"BadRequest","message":"Offer with PublisherId: redhat, OfferId: osa-preview cannot be purchased due to validation errors. See details for more information.
...
```

Updating since origin sku was removed.

---

Makefile

Change the default target into `make <all>` so we could just call `make` in ci testing and we manage it in code, comparing to the template 
@kargakis

makefile default target change

---

cmd/createorupdate/createorupdate.go
cmd/healthcheck/healthcheck.go
cmd/sync/sync.go
pkg/api/plugin.go
pkg/plugin/plugin.go
pkg/validate/validate.go
pkg/validate/validate_test.go

Skips validation for post-enrichment items like FQDN and routerProfile.FQDN
Fixes: https://github.com/openshift/openshift-azure/issues/209
@jim-minter  @amanohar @shrutir25

Add external only flag to validation

---

cmd/createorupdate/createorupdate.go
pkg/api/plugin.go
pkg/plugin/plugin.go
pkg/validate/validate.go

@pweil- comments on the merging<->validation order: 
1. we need to merge the old cs.Config into the new and hand that over to GenerateConfig (so there is no merging of the user request but of the generated config). 
2. validation only happens on the user request and not on generated config. 
3. In the close future, we probably want to add validation for updates and likely invalidate every request that causes a difference in fqdn, resourceGroup, and location. If we are going to merge user requests prior to validation, we will not be able to validate updates.  
Based on the above I don't see what merging gives us prior to validation (since the merged part is unaffected by validation) and I prefer to avoid the extra method in the plugin interface so I just opted on …

Merge old and new config + validate updates

---

hack/create.sh

Ci operator uses create.sh to create cluster. 
Purge uses `tag` to clean them. 
I would suggest to add this tag to our projects so we relay under same purge job rules:
`groupTimeout   = 3 * 24 * time.Hour`
This implied each cluster will be deleted after 3 days of creation. If you want cluster for longer time - remote the tag, or change the value.

add tag for purge jobs

---

pkg/checks/checks.go
pkg/healthcheck/healthcheck.go

```
INFO[0000] starting health check                         resourceGroup=pweilosa
INFO[0001] checking infrastructure service health        resourceGroup=pweilosa
INFO[0001] checking  "prometheus-node-exporter"          resourceGroup=pweilosa
INFO[0001] checking  "sync"                              resourceGroup=pweilosa
INFO[0001] checking  "ovs"                               resourceGroup=pweilosa
INFO[0001] checking  "sdn"                               resourceGroup=pweilosa
INFO[0001] checking  "prometheus"                        resourceGroup=pweilosa
INFO[0131] checking  "docker-registry"                   resourceGroup=pweilosa
INFO[0131] checking  "registry-console"                  resourceGroup=pweilosa
INFO[0131] checking  "router" …
```

add health check logging

---

cmd/createorupdate/createorupdate.go
cmd/createorupdate/deploy.go
cmd/createorupdate/update.go
pkg/api/plugin.go
pkg/api/types.go
pkg/arm/arm.go
pkg/config/upgrade.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

Suggestion to start using Context with all external methods we have. Some of them at the moment does not have use for context,  but I added ctx object too just to keep consistent api. 
The external consumer should not care about how context is being used. And by introducing it early we can use it later. 
At the moment context flow:
`createorUpdate` -> `plugin`-> `GenerateARM` -> `arm.Generator`
`createorUpdate` -> `plugin`-> `MergeConfig` 
`createorUpdate` -> `plugin`-> `Validate` 
`createorUpdate` -> `plugin`-> `GenerateConfig`
`createorUpdate` -> `plugin`-> `InitializeCluster` -> `intitialize.Initializer`
`createorUpdate` -> `plugin`-> `HealthCheck` -> `healthcheck.Healthchecker`
`createorUpdate` -> `plugin`-> `Drain` -> `upgrade.Upgrader`
`createorUpdate` -> `plugin`-> `WaitForReady` …

Property bag/Context

---

Makefile

Stopgap solution for building and pushing sync using short commit IDs for tags.
@openshift/sig-azure 
```
git checkout commit_id
make sync-push
```
should push a sync image built from commit_id.
Ref https://github.com/openshift/openshift-azure/issues/327

make sync-image: tag sync image with commit id

---

cmd/createorupdate/createorupdate.go
pkg/config/images.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

Fixes https://github.com/openshift/openshift-azure/issues/327
@openshift/sig-azure this PR moves `SYNC_IMAGE` out of the plugin code and uses the plugin struct to hold the sync image.

Configure sync image pullspec in plugin init 

---

hack/config.sh
hack/delete.sh
hack/ssh.sh

with this change
* `hack/ssh.sh` takes you straight in to your master-000000. `hack/ssh.sh othercluster` downloads the config for othercluster and takes you in to master-000000 on that cluster. `-n {0,1,2}` allows you to ssh onto a different master
* `hack/delete.sh` no longer requires an argument
shout out to @charlesakalugwu for pointing out the shortcomings of our hack/ scripts and to @mjudeikis for hack/config.sh.  These are your ideas.  @charlesakalugwu this doesn't replace you doing the `env` pieces of issue #399 although hopefully it helps.
fixes #411

allow ssh into arbitrary clusters, stop requiring resourcegroup on delete

---

.gitignore
Dockerfile.sync
Makefile

Fixes https://github.com/openshift/openshift-azure/issues/424
A change in release is required to mount the COMMIT_ID correctly in CI images.

Record short commit id on every sync build

---

hack/ssh.sh

`hack/ssh.sh` on its own doesn't work without this fix.  Not quite sure how I missed that :(

fix daft mistake in ssh.sh

---

.gitignore
Dockerfile.sync
Makefile
cmd/sync/sync.go

@kargakis @kwoodson I was hoping to do it this way so the commit goes straight into the logging

use -X to store sync commit

---

pkg/upgrade/deploy.go
pkg/upgrade/update.go

Since WaitForCompletion directly calls WaitForCompletionRef just find/replace the functions.
Closes #290 
Signed-off-by: Angus Salkeld <angus@salkeld.id.au>

Replace WaitForCompletion with WaitForCompletionRef

---

pkg/api/marshal.go

grown several unpleasant hacks

refactor config marshalling: it was not honoring the json tag names and had

---

hack/create.sh

@mjudeikis @jim-minter this should allow us to use a tight TTL for resource groups created in CI tests.
/cc mjudeikis

Tag resource groups with a TTL

---

OWNERS

The OWNERS file in this repo is automatically synced in
openshift/release where we need to use automated labeling
of PRs touching azure-related config. OWNERS files provide
support for automated labeling and this change enables that.
/cc @mjudeikis

Add OWNERS labeling

---

test/e2e/extended_suite_test.go
test/e2e/osa_test.go

@jim-minter @mjudeikis @kwoodson first step to make our e2e suite run based on the type of the user (end-user, SRE) is to stop accessing the content of the config blob and require only a kubeconfig. In a follow up we should start reading the azure credentials from the environment in order to use the azure SDK for tests that are going to need it.

Start using kubeconfig in tests vs cluster config

---

Makefile
hack/e2e.sh
test/e2e/admin_test.go
test/e2e/client_test.go
test/e2e/end_user_test.go

Split out of https://github.com/openshift/openshift-azure/pull/428
@jim-minter @mjudeikis the idea here is to run all e2e suites as part of our merge queue (hence `hack/e2e.sh`) while allowing to run tests both inside a cluster and given a kubeconfig. For now I am assuming that if the provided kubeconfig is not system:admin or the azure cluster reader, it's an end user. PTAL, I think we can get this merged as is and iterate on the e2e user tests with the addition of openshift client-go.

Split e2e framework to run different suites based on provided kubeconfig 

---

pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

fixes #541 
This should have been caught by a test.  AZURE-135 will rework all of this area, and I have added the requirement for such a test there.

fix missing NetworkProfile merge

---

.gitignore
hack/e2e.sh
test/e2e/end_user_test.go

@mjudeikis @jim-minter @asalkeld this should stop flakying tests in PRs and at the same time continue to run the test in order to debug.
/cc mjudeikis jim-minter asalkeld

Disable PDB error check in e2e

---

pkg/api/2018-09-30-preview/api/types.go
pkg/api/types.go

closes #433 
@amanohar can you let me know if this is what you are after?
I was unsure what we should put into the unversioned api, maybe "unversioned" instead of "master"..

Define APIVersion in the api packages

---

hack/delete.sh

this got me already few times!
If you have created cluster `cluster-prod` but want to clean old cluster `cluster-dev` and execute:
`./hack/delete.sh cluster-dev` your prod cluster is dead :)

add flag for delete.sh

---

cmd/createorupdate/createorupdate.go
pkg/fakerp/fakerp.go

I need to keep my changes small in between PRs so here I am simply moving the logic of the fake RP into its own package. It's unclear to me now whether this is going to be reused by the e2e framework but my thinking is to move code out of cmd/createorupdate/createorupdate.go, turn it into an http server, and use a separate process to do the PUT request.
/cc jim-minter

Move createOrUpdate in pkg/fakerp

---

Makefile
cmd/logbridge/main.go

* ensure that sync and logbridge include a git identifier with clean/dirty info
* protect against crash in #581 where it looks like cursor file is empty
* add logging to understand how crash happened

protect against state/cursor being empty and add logging

---

hack/create.sh
hack/upgrade.sh

The flag was removed in https://github.com/openshift/openshift-azure/pull/572

Remove redundant flag from hack scripts

---

pkg/config/util.go

Fix for no newline character at end of htpasswd's osadmin line.
fixes #589

Adding new line character to htpasswd.

---

.gitignore
env.example
hack/config.sh
hack/create.sh
hack/delete.sh
hack/dns.sh
hack/scp.sh
hack/ssh.sh

* add NOGROUPTAGS option to prevent tagging groups with now/ttl (to avoid creating management subscriptions and having them accidentally cleaned up by azure-purge)
* ￼ignore env.* files (to define parameters for management subscriptions in separate env.something files)
* allow overriding of --subscription used by az commands

Miscellaneous fixes necessitated by addition of prod subscription

---

.gitignore
Makefile

@asalkeld this change should help us start collecting coverage profiles in CI tests w/o trying to open the profile in html. There is also one update that needs to happen in openshift/release.
/cc asalkeld

Generate coverage profile during unit tests

---

cmd/createorupdate/createorupdate.go

@openshift/sig-azure this change transforms our fake rp to run as an http server. In a follow-up PR I am planning on removing the http client in favor of the osa sdk. I am also thinking whether separating the client into its own process makes sense from a testing standpoint.
Part of https://jira.coreos.com/browse/AZURE-165

Transform fake RP into an http server

---

hack/create.sh

When I try to use the OSA sdk and the manifest we currently generate to start a cluster via the prod RP, I get the following error:
```
containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="MismatchingResourceName" Message="The provided resource name 'openshift' did not match the name in the Url 'kargakisprode2es'."
```
Seems that the prod RP requires name to match the resource group. I can start clusters successfully with this change.

Prod RP requires name to match resource group

---

pkg/addons/client.go
pkg/addons/client_test.go

Fixes #504
We don't want secret values to be logged *anywhere*

Don't print the diff if the object kind is Secret

---

hack/upgrade.sh

We started using provisioningState in the fake RP to ensure the OSA SDK is working properly when querying the RP (https://github.com/openshift/openshift-azure/pull/592) but since we now write it down in manifest.yaml, upgrade.sh picks it up and fails to validate.
Fixes https://github.com/openshift/openshift-azure/issues/636

Delete provisioningState before an update

---

Makefile
cmd/createorupdate/createorupdate.go
hack/create.sh
hack/delete.sh
test/e2erp/client_test.go
test/e2erp/e2erp_suite_test.go

In the first commit, I am separating cluster creation/deletion from the RP test suite to align with what we already do in the openshift e2e suite. An update is required for this in openshift/release to make use of the new make target.
In the second commit, I am enabling updates and cluster cleanups in a single createorupdate run which will potentially simplify our e2e templates and enable us to run upgrade tests locally w/o the need to use our ci-operator templates.
If it's too much to have these in a single PR, I can separate one of the commits to a different PR.

Prod cluster test cleanup and createorupdate enhancement

---

cmd/createorupdate/createorupdate.go
hack/upgrade.sh

Fixes https://github.com/openshift/openshift-azure/issues/654
Empirically our upgrade test takes from 35m up to 40-45m.

fakerp timeout extended to 1 hour

---

cmd/createorupdate/createorupdate.go
hack/create.sh
hack/delete.sh
hack/upgrade.sh
pkg/util/mocks/mock_azureclient/azureclient.go

Collapsing some parts of our bash scripts in createorupdate and enabling random region selection to ensure in our tests we can deploy clusters in every supported region.

createorupdate: env checks and random region selection

---

env.example
hack/create.sh
hack/upgrade.sh
test/manifests/normal/create.yaml

I am moving the manifest out of hack/create.sh into `test/manifests` where we can place more manifests to test different flows (eg. custom vnet, different types of upgrades, etc.). Then, in order to actually write a test that would make use of a different manifest rather than the default we would place the manifest inside `test/testdata/{somename}/create.yaml` and set `MANIFEST=test/testdata/{somename}/create.yaml` in the prow job to make use of that request during cluster deployment. More work needs to be done to enable upgrades, will do in a follow-up.
/cc @kwoodson @jim-minter @cjryan @mjudeikis

Move OSA request manifest out of hack/create.sh

---

pkg/addons/translate.go
pkg/api/2018-09-30-preview/api/types.go
pkg/api/default.go
pkg/api/types.go
pkg/api/validate.go
pkg/api/validate_test.go
pkg/config/derive.go
pkg/config/derive_test.go

Allow master and infra nodes to be Standard_D{2-64}s_v3.
Allow a range of additional values for compute nodes.
Increase maximum number of compute nodes to 20.
See code for rationales.

add additional VM flavours and increase maximum number of compute nodes

---

test/e2e/client_test.go
test/e2e/conditions_test.go
test/e2e/end_user_test.go

Fixes #645 
This should:
* Deploy a template with persistent storage
* Get the ingress routes from the deployment
* Hit the routes several times, ensuring the visit counter increments
* Kill the database pod
* Wait for the pod to come back
* Hit the route again a few times

Adding another e2e test

---

pkg/cluster/deploy.go
pkg/cluster/drain.go
pkg/cluster/drain_test.go
pkg/cluster/ready.go
pkg/cluster/ready_test.go
pkg/cluster/update.go

fixes #741
the 2nd commit is the key one here.  The idea is to introduce a new type for computer names - we have to remember to wrap all reads of ComputerName as `computerName(*vm.VirtualMachineScaleSetVMProperties.OsProfile.ComputerName)` but then we are reminded that we must do `computerName.toKubernetes()` whenever we want to use a computer name as a kubernetes node name.

fix computer name / node name issues and tidy up

---

test/e2e.sh

This broke the update test since EXEC is undefined and the go flag parsing would not interpret the last half of the flags.
/cc mjudeikis charlesakalugwu

Remove quotes from bash envs to fix Go flag parsing

---

test/e2erp/client_test.go
test/e2erp/realrp_test.go

This spec will ensure a user cannot read the config blob from the
storage account (or read the storage account at all)

Add another spec to e2erp

---

cmd/sync/sync.go
pkg/api/validate.go
pkg/api/validate_test.go
pkg/plugin/plugin.go

Fixes #707 
This should error out when requesting StandardD2sV3 in production
environments, as that size is only really useful for QA/testing

Make it so StandardD2sV3 can only be used in test

---

cmd/createorupdate/createorupdate.go
pkg/fakerp/config.go
pkg/fakerp/server.go

Also:
* fix resource group deletion to exit successfully if the resource
group is already deleted (fixes https://github.com/openshift/openshift-azure/issues/698)
* use the delete future appropriately

Add NO_WAIT functionality for DELETEs

---

hack/e2e.sh

As a follow-up to #780 this change allows configurable timeouts for e2e tests. Particularly useful for the update-based scenarios.
For an update test we can use the following make target utilizing the TIMEOUT
```
e2e-keyrotation:
FOCUS=KeyRotation TIMEOUT=60m ./hack/e2e.sh
```

Enable configurable timeouts for e2e tests

---

test/e2e/specs/customer_admin.go
test/e2e/specs/customer_reader.go
test/e2e/specs/end_user.go
test/e2e/specs/fakerp/admin.go
test/e2e/specs/realrp/realrp.go

Otherwise we risk allowing failed tests to succeed in CI eg. https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/794/pull-ci-openshift-openshift-azure-master-e2e-azure-keyrotation/1 failed with 
```
S [SKIPPING] in Spec Setup (BeforeEach) [0.001 seconds]
Key Rotation E2E tests [KeyRotation] [Update]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/updates/keyrotation/keyrotation.go:23
should be possible to maintain a healthy cluster after rotating all credentials [BeforeEach]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/updates/keyrotation/keyrotation.go:40
failed to get oauth token from client credentials: parameter 'clientID' cannot be empty
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/updates/keyrot …
```

Avoid skipping errors in the e2e framework

---

pkg/api/2018-09-30-preview/api/client.go
test/manifests/normal/scaleup.yaml

Managed to scale up a cluster with the following partial request. @charlesakalugwu we should probably reuse it since that's how scale up requests are going to look like when they land in the prod RP.
/cc jim-minter charlesakalugwu

Enable partial requests to update clusters

---

cmd/createorupdate/createorupdate.go

We should handle possible errors from os.Setenv in `cmd/createorupdate.go`
/cc @mjudeikis @kargakis

Handle possible errors from os.Setenv

---

cmd/createorupdate/createorupdate.go
pkg/fakerp/config.go
pkg/fakerp/directory.go
pkg/fakerp/directory_test.go
pkg/fakerp/manifest.go

**What type of PR is this?**
/kind feature
**What this PR does / why we need it:**
To ensure that our fake rp works from either `cmd/createorupdate.go` or E2E tests in `test/e2e` we need to standardize how the fake rp finds the various core/config directories it needs for its operation. This PR introduces a function which allows a client to discover the absolute path to any named folder within the directory hierarchy of the caller. 
**Which issue(s) this PR fixes:**
Fixes #826 
**Release note:**
```
allow fake rp to find core/config directories recursively within its directory hierarchy
```

Find core fakerp directories recursively

---

pkg/cluster/initialize.go
pkg/cluster/initialize_test.go
pkg/cluster/types.go
pkg/cluster/updateblob.go
pkg/cluster/updateblob_test.go

Avoid storing the Blob object in the simpleUpgrader, evidently this was a
mistake.  On a Blob.Get() the blob MD5 is latched into the Blob object.  If
Blob.CreateBlockBlobFromReader() is called, the latched MD5 is not cleared,
resulting in an error on the subsequent Get().  Store the Container in the
simpleUpgrader to force the user to get the Blob themselves.

Follow-up to https://github.com/openshift/openshift-azure/pull/818

---

pkg/fakerp/config.go

Should allow us to set it to false explicitly in [tests](https://github.com/openshift/release/pull/2309).

Set RUNNING_UNDER_TEST only when true

---

cmd/sync/sync.go
pkg/addons/addons.go
pkg/addons/client.go
pkg/addons/client_test.go
pkg/cluster/deploy.go
pkg/cluster/types.go
pkg/cluster/update.go
pkg/util/managedcluster/managedcluster.go
pkg/util/wait/wait.go
pkg/util/wait/wait_test.go
test/e2e/specs/end_user.go

Attempt at catching and handling the x509 error returned by the healthz check for a cluster.
Fixes https://github.com/openshift/openshift-azure/issues/527

Catch, retry, and log the x509 exception.  Small refactor.

---

hack/delete.sh
hack/etcdrecovery.sh
hack/upgrade.sh

Yesterday we pushed [a change in our e2e job](https://github.com/openshift/release/pull/2312) that drops `az login` from both cluster creation and deletion since it's not required anymore. Unfortunately, our delete.sh script has an artifact use of az that broke cluster deletion. 
/cc @charlesakalugwu @mjudeikis @jim-minter

Remove az dependency from hack/delete.sh

---

cmd/createorupdate/createorupdate.go
hack/create.sh
test/e2e/specs/realrp/realrp.go

Fixes https://github.com/openshift/openshift-azure/issues/869
This will allow us to continue using random region selection in our tests.

Set region from the external manifest in e2e tests if unset

---

pkg/util/azureclient/resources.go
test/clients/azure/client.go
test/e2e/specs/realrp/realrp.go

Should this loop over general `ResourcesClient.List()` instead? (e.g. _all_ resources in the subscription?)
@kargakis @jim-minter @charlesakalugwu ptal

Make sure enduser can't delete any azure resources

---

cmd/createorupdate/createorupdate.go
pkg/fakerp/manifest.go
test/e2e/specs/fakerp/keyrotation.go

This adds support for reading manifest files containing templated values coming from environment variables in the keyrotation e2e tests
/cc @kargakis

Support templated manifests in keyrotation e2e

---

Makefile
pkg/fakerp/fakerp.go
test/clients/azure/client.go
test/e2e/specs/customer_admin.go
test/e2e/specs/customer_reader.go
test/e2e/specs/end_user.go
test/e2e/specs/fakerp/admin.go
test/e2e/specs/fakerp/keyrotation.go
test/e2e/specs/realrp/realrp.go
test/e2e/specs/scaleupdown.go
test/util/log/log.go

We will also need a test where an actual upgrade is invoked and at the end we ensure the update blob is different than what it was before the update.

Add re-entrancy check e2e test

---

.gitignore
Dockerfile.e2e
Makefile

This adds a dockerfile and make targets for building the e2e tests, creating an image and pushing the image to quay. Coreesponding CI updates will be done in a follow-up.
/cc @kargakis @jim-minter

Add e2e image and make targets

---

pkg/fakerp/directory.go
pkg/fakerp/directory_test.go

I discovered this while working out how to run our e2e tests from a
container. walkParents was checking if the path we are analysing is the
system root (/) and exits if it is. The problem with this is that the
sought-after directory could be at root directory e.g. in a container at
/_data
This fix reverses the order of the stop condition in walkParents and allows
an e2e binary in a container (at /e2e) to find the _data or secrets
directories at /_data or /secrets in the container.

Fix fakerp.FindDirectory to find folders at system root

---

hack/create.sh
hack/delete.sh
hack/upgrade.sh

@jim-minter @mjudeikis @charlesakalugwu this is the best approach I can come up with that does not involve:
* adding extra logic in the fake RP (https://github.com/openshift/openshift-azure/pull/926)
* using less cross-platform tools like `fuser` (https://github.com/openshift/openshift-azure/pull/927)
I am also trying to workaround the fact that we are using bash by replacing the callout to `hack/fakerp.sh` with using `go run` directly because running bash inside of bash is super slow and the $(lsof) subshell in the trap may not resolve correctly since the server has yet to start. The current approach is still a little racy but it avoids using weird wait logic for the server to come up in order to get the pid. Also, for some reason the process id returned from the async process execution …

Trap killing process on 8080

---

cmd/createorupdate/createorupdate.go
pkg/fakerp/client/manifest.go
test/e2e/specs/fakerp/admin.go
test/e2e/specs/fakerp/keyrotation.go
test/e2e/specs/realrp/realrp.go
test/e2e/specs/realrp/vnetpeering.go
test/e2e/specs/scaleupdown.go

Since defaulting is only used in createorupdate and
every test is using its own manifest, it makes sense
to simplify the helper and move the defaulting logic
in createorupdate.

Simplify manifest helpers

---

pkg/api/2018-09-30-preview/api/types.go
pkg/api/2018-09-30-preview/api/types_test.go
pkg/api/admin/api/types.go
pkg/api/admin/api/types_test.go
pkg/api/converterfromadmin.go
pkg/api/converterfromv20180930preview.go
pkg/api/converterfromv20180930preview_test.go
pkg/api/convertertoadmin.go
pkg/api/convertertov20180930preview.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/validate.go
pkg/api/validate_test.go
pkg/arm/resources.go
pkg/plugin/plugin.go
pkg/util/resourceid/resourceid.go

Fixes #544 
Adding the VnetID field to all 3 APIs, converters, validator, unit tests. Also the code to populate the field + subset of the azure Network client.

adding VnetID field to APIs and code to populate it after deploy

---

docs/e2e/requirements.md
test/e2e/specs/scaleupdown.go
test/manifests/normal/scaledown.yaml
test/manifests/normal/scaleup.yaml

Avoid reading from the filesystem in order to make
scale up and down requests. We stop using partial
requests but at the same time enable the test to
work with prod environments and not needing external
files.
/cc @charlesakalugwu @jim-minter

Update scale test to be self-contained

---

pkg/arm/resources.go

I don't think this will fundamentally change our performance, but I also think it's better on than off.

enable r/o cache on etcd disk

---

pkg/fakerp/fakerp.go

This populates clusterID field same as realRP.
In preparation for https://github.com/openshift/openshift-azure/issues/1011 to have same data in realRP and fakeRP

populate cluster id

---

Makefile
README.md
codecov.yaml
hack/codecov-report.sh

This prepares the openshift-azure project for codecov integration. 
Before merging, we need to do the following:
See a working example of codecov PR comments, linking, the codecov badge amongst other things at: https://github.com/charlesakalugwu/codecov/pulls?q=is%3Apr+is%3Aclosed
/cc @kargakis @mjudeikis @jim-minter 
/hold

Setup codecov integration

---

pkg/arm/arm.go
pkg/arm/resources.go
pkg/arm/resources_test.go

This PR:
1) updates to use outbound rules instead of dummy inbound rules to make our worker vm internet connectivity work
2) switches on "enableTCPReset" - I'll be interested to see if this alters the behaviour of #560.  Ssee https://docs.microsoft.com/en-US/azure/load-balancer/load-balancer-tcp-reset for more info

update lb rules

---

cmd/sync/sync.go
pkg/api/validate/admin.go
pkg/api/validate/api.go
pkg/api/validate/plugin.go
pkg/api/validate/plugin_test.go
pkg/api/validate/types.go
pkg/api/validate/update_validators.go
pkg/api/validate/validate_test.go
pkg/api/validate/validators.go
pkg/plugin/plugin.go

This PR is proposal basis for now:
- Splits Validators to sub-package inside api package
- Splits 3 validators to separate interfaces
- has reusable validator functions for adminAPI and API
- isolates use of `RunningUnderTest` variable from validators to keep it to minimal. 
PR is built on top of https://github.com/openshift/openshift-azure/pull/922 as a follow-up 
fixes: https://github.com/openshift/openshift-azure/pull/922
/cc @jim-minter @kargakis @charlesakalugwu WDYT?

Validators split

---

README.md

Cannot move the CI docs in openshift-azure since all the ci config resides in release.

Add link to OSA CI doc

---

pkg/arm/resources.go

This should in theory give us an IOPs increase up to 1100 according to
https://azure.microsoft.com/en-us/pricing/details/managed-disks/

Increasing size of etcd disks to 256G

---

pkg/cluster/update_master.go
pkg/cluster/update_master_test.go

closes #1068
/cc @jim-minter @kargakis @asalkeld @mjudeikis

Avoid setting VMScaleSetVMReimageInput during master VM reimaging

---

pkg/api/admin/api/config.go
pkg/api/admin/api/types_test.go
pkg/api/config.go
pkg/api/converterfromplugin.go
pkg/api/converterfromplugin_test.go
pkg/api/convertertoadmin.go
pkg/api/plugin/api/config.go
pkg/api/types_test.go
pkg/api/validate/plugin.go
pkg/api/validate/plugin_test.go
pkg/api/validate/types.go
pkg/api/validate/types_test.go
pluginconfig/pluginconfig-311.yaml
test/e2e/specs/fakerp/admin_api.go

This adds an internal version field to tracking plugin code versions we will use for the release process. 
Was considering adding it into the main `ManagedOpenshiftCluster` object, but because its total internal type did it in the `Config` struct instead. 
https://docs.google.com/document/d/1einHXiv6r6tI5i1ce_PkZybmCYOWAqtYz5bgzWhKr5Q/edit#heading=h.6jiuaxjhr1fc

add clusterVersion field to tracking

---

hack/ssh.sh

SSH-add should run always to add keys into the ssh daemon, not only when its upgrade or variable is not set. 
issue:
If you run `./hack/ssh.sh rg_name` RESOURCEGROUP variable is set and there is no ssh key adding. So ssh will fail.
If you run `./hack/ssh.sh` it will work as a variable is being evaluated from yaml file.

fix ssh script

---

pkg/config/derive.go
pkg/config/derive_test.go
pkg/util/cloudprovider/cloudprovider.go

fixes: https://github.com/openshift/openshift-azure/issues/1087
When creating internal LB this is the query to Azure: 
```
[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('vnetName'), parameters('subnetname'))]",
```
Our cloud provider does not have `vnetName` and ` subnetName` set so we ended with "" values.
And so the error:
```
Subnet "" not found with message: "network.SubnetsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Network/virtualNetworks/subnets' under resource group '5786a402-a88d-4cac-b8f9-ae2a4226a531' was not found.\""
```
This should solve this. Will raise follow-up issue to tide-up constants for vnet names and …

ILB creation issue

---

Makefile

Before this fix, I saw the following error at the top of every make invocation
```
charles@titan:~/Documents/go/src/github.com/openshift/openshift-azure$ make generate
CLUSTER_VERSION is v0.0
/bin/sh: 1: [[: not found
TAG set to v0.0
go generate ./...
bindata.go
```
/cc @mjudeikis @kwoodson @Makdaam

Fix makefile for debian-based systems

---

Dockerfile.azure-controllers
Dockerfile.e2e
Dockerfile.etcdbackup
Dockerfile.metricsbridge
Dockerfile.sync

Moving our base images from centos to rhel.  @pweil- sent me a link to origin and their image building here(https://github.com/openshift/origin/blob/master/images/base/Dockerfile.rhel7).  This uses a rhel7 base image which lives on registry.access.redhat.com.

Moving docker images from centos to rhel base.

---

Makefile

remove dev namespace for now. too many moving parts. maybe later we bring it back
/cc @charlesakalugwu @Makdaam

remove dev namespace

---

pkg/api/2018-09-30-preview/api/types.go
pkg/api/admin/api/types.go
pkg/api/types.go
pkg/api/validate/validators.go
pkg/fakerp/admin_handlers.go
pkg/fakerp/util.go

This adds the `AdminUpdating` provisioning state to the internal api types. This will "allow us as engineers to look up clusters logs and distinguish between a regular update operation and an admin update operation. Also it will be used to block a regular put operation when an admin update operation is ongoing."
closes #1058 
/cc @mjudeikis @Makdaam @jim-minter

Add AdminUpdating provisioning state

---

pkg/fakerp/admin_handlers.go

Remove/rollback `adminUpdate` state as this sets "provisioningState" inside containerservices.yaml and if test is running in the wrong order, this is causing next tests to rotate nodes.
Example:
A subset of tests ran before and now we have modified provisioning state (local and cluster) so it will trigger node rollout.
```
→ diff _data/containerservice.yaml _data/containerservice.yaml_bckp                                                                                                                                                
178d177                                                                                                                                                                                                            
<   provisioningState: AdminUpdating     
```
Need …

rollback use of UpdateStatus

---

pkg/cluster/healthcheck.go
pkg/fakerp/dns.go
pkg/fakerp/fakerp.go
test/manifests/normal/create.yaml

In preparation for the upcoming work for vanity domains, we would like to align our DNS setup to mirror what the real RP does.  This includes creating a DNS zone with a random name and placing it inside of the resource group beside the cluster.

DNS refactor in preparation for vanity domains.

---

pkg/api/plugin.go
pkg/cluster/types.go
pkg/fakerp/admin_handlers.go
pkg/fakerp/config.go
pkg/fakerp/customer_handlers.go
pkg/fakerp/dns.go
pkg/fakerp/fakerp.go
pkg/util/azureclient/azureclient.go

The Authorizer comes in from the RP and is passed to the plugin for
subsequent requests. Before, the autorest.Authorizer object was created
using credentials harvested by the plugin.
In this PR, the fakerp package is also altered in order to pass along an
RP generated autorest.Authorizer mocked by enrichContext(). Otherwise,
the internal communication of the credentials is done via the
GetAuthorizerFromContext() routine.
Signed-off-by: Yannick Cote <ycote@redhat.com>

Allow RP credentials to be used in plugin

---

pkg/arm/resources.go
pkg/cluster/hash.go
pkg/cluster/ready_test.go
pkg/cluster/scaler/scaler.go
pkg/cluster/scaler/scaler_test.go
pkg/cluster/update_master.go
pkg/cluster/update_master_test.go
pkg/cluster/update_worker.go
pkg/cluster/update_worker_test.go
pkg/util/azureclient/compute.go
pkg/util/azureclient/compute_addons.go
pkg/util/mocks/mock_azureclient/azureclient.go
pkg/util/mocks/mock_scaler/scaler.go
test/e2e/specs/realrp/realrp.go

An updated azure compute sdk is required for a few of the proposed geneva action implementations (https://github.com/openshift/openshift-azure/pull/1085 and  https://github.com/openshift/openshift-azure/pull/1091).
This PR updates the compute sdk to `2018-10-01` and also takes a stab at solving the `Reimage` parameter issue which was added [here](https://github.com/openshift/openshift-azure/pull/1064) and was attempted to be solved [here](https://github.com/openshift/openshift-azure/pull/1069). The eventual workaround can be found [here](https://github.com/openshift/openshift-azure/pull/1070)
After getting merged, related open geneva-related PRs (e.g. [this](https://github.com/openshift/openshift-azure/pull/1085)) would need to rebase to pull in the compute updates.
/cc @mjudeikis …

Update azure compute api

---

pkg/arm/resources.go

Error in new deployment now:
```
azure_loadbalancer.go:806] reconcileLoadBalancer: reconcileLoadBalancer for service(default/router): lb(kubernetes) - updating                                                                                                                                             
azure_backoff.go:364] processHTTPRetryResponse: backoff failure, will retry, HTTP response=400, err=network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="EnableTcpResetCannotBeSpecifiedForApiVersion" Message="Spe
cified api-version 2017-09-01 does not meet the minimum required api-version 2018-07-01 for EnableTcpReset property." Details=[] …
```

remove tcp reset

---

Dockerfile.azure-controllers
Dockerfile.e2e
Dockerfile.etcdbackup
Dockerfile.metricsbridge
Dockerfile.sync

As a follow on to #1095 and #1121, we need to ensure our images are at a specific patch level in order to keep them up to date.
The issue here is that our images are being built on an older image without the latest packages.  We should either move to a version or use latest.

Force azure image builds onto latest rhel7 image.

---

pkg/fakerp/shared/shared.go
test/clients/openshift/client.go
test/clients/openshift/login.go
test/e2e/specs/customer_admin.go
test/e2e/specs/customer_reader.go
test/e2e/specs/end_user.go
test/e2e/specs/fakerp/admin.go
test/e2e/specs/fakerp/etcdrecovery.go
test/e2e/specs/fakerp/keyrotation.go
test/e2e/specs/fakerp/prometheus.go
test/e2e/specs/scaleupdown.go
test/e2e/standard/cluster.go
test/e2e/standard/sanitychecker.go
test/e2e/standard/testapps.go

This work enables MSFT to call functions to "sanity check" a cluster as part of their e2e tests.
*Notable Changes*
* A new deep test interface in `test/clients/interface.go`
* A new deep test client in `test/clients/openshift/client.go`
* The deep test client wraps all the previous openshift clients we used for e2e tests
* A new deep test client can be created with `NewClient(log *logrus.Entry, cs *internalapi.OpenShiftManagedCluster)`
* If developing against the fake rp (RH), sensible defaults will be set for log and cs when you call `NewClient(nil, nil)`
* If developing against the real rp (MSFT), you can provide your log and cs and call `NewClient(log, cs)`
* Conforming to the deep test interface, the deep client provides the following methods
* `CreateTestApp(ctx context.Context) …

Deep e2e test integration

---

pkg/fakerp/admin_handlers.go

This adds a `WriteHelpers` method to the `Generator` interface in `pkg/config`. The method is called from `plugin.GenerateConfig` which therefore ensures that the plugin's `CreateOrUpdate` or other config altering calls such as `RotateClusterSecrets` result in updated ssh keys, kubeconfigs etc being laid down on the machine. This will allow an operator to ssh into any VM during a key rotation run.
/closes #1167
/cc @mjudeikis @jim-minter @mgahagan73

Move writeHelpers to config generator

---

Makefile

This deletes the _data directory after `make delete` is called to delete a cluster
/cc @mjudeikis @kwoodson

Delete _data dir from make delete

---

test/e2e/specs/end_user.go
test/e2e/specs/fakerp/etcdrecovery.go
test/e2e/specs/fakerp/keyrotation.go
test/e2e/specs/scaleupdown.go

This changes the error checks in our e2e tests from `Expect(len(errs)).To(Equal(0))` to `Expect(errs).To(BeEmpty())`
/cc @mjudeikis @jim-minter @kwoodson @thekad

Fix e2e test error messages

---

Makefile
pkg/api/plugin.go
pkg/cluster/initialize.go
pkg/cluster/types.go
pkg/fakerp/admin_handlers.go
pkg/fakerp/routes.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go
pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
pkg/util/mocks/mock_cluster/types.go
test/e2e/specs/fakerp/forceupdate.go

This work implements a geneva action that allows an admin to force-update a cluster by resetting/zeroing the cluster's update blob prior to calling update.
This is part of AZURE-257
/cc @mjudeikis @Makdaam @thekad @jim-minter

Geneva action force-rotate cluster

---

Makefile

The 'all-image' Makefile target is broken due to an apparent change of name from metrics-image to metricsbridge-image.

Fix 'all-image' Makefile target: metricsbridge-image.

---

README.md
cmd/createorupdate/createorupdate.go
cmd/sync/sync.go
env.example
hack/aad.sh
pkg/controllers/customeradmin/group_mapping.go
pkg/fakerp/client/aad.go
pkg/fakerp/client/config.go
pkg/fakerp/client/groups.go
pkg/util/azureclient/azureclient.go
pkg/util/configblob/container.go

remove hack/aad.sh app-{update,delete} - these are no longer used
Remove hard coded AAD application ID
* jminter-team-shared app now has permissions to modify AAD apps it owns
* hence can remove hard coded AAD application ID
* removes need to store AZURE_USERNAME and AZURE_PASSWORD in cleartext, hooray!
* newly created AAD apps must be marked as owned by jminter-team-shared: updated aad.sh app-create to do that

Remove hard coded AAD application ID

---

Makefile

to prevent stale go binaries inside docker images.

adding startup related targets to .PHONY

---

hack/codecov-report.sh

This configures our codecov reporting to send the right reports based on the prow job type.
For presubmit jobs (dealing with PRs), PR-specific prow environment variables are set and these are a bit different from the postsubmit job's. 
This also sends job url, job id and build id to codecov
/cc @jim-minter @kwoodson

Send codecov report based on prow job type

---

.codecov.yml

Ignores the generated `bindata.go` files from codecov analysis

Ignore certain files from codecov analysis

---

cmd/metricsbridge/metricsbridge.go

Adding calculating of the metric's rate of change (for counter metrics).
This can be activated for a given metric by setting calculate_rate to true.
My suggestion is that the new metric should have a '_rate' suffix instead of the '_total' suffix.
Example definition in the configmap:
```
- query: 'container_cpu_user_seconds_total{namespace=~"default|openshift|openshift-.+|kube-.+|", container_name!="", container_name!="POD"}'
calculate_rate: true
name: 'container_cpu_user_seconds_rate'
```
I'll open the configmap PR after the new image of metricsbridge is built.
the query to Prometheus is replaced with:
(%s - %s offset 1m) or (%s unless %s offset 1m)
How it behaves:
In case there is a current value and a value 1 min ago (for the same value of dimensions/labels) calculates the difference …

metricsbridge - adding an option to calculate rate of a metric

---

test/manifests/fakerp/create.yaml

only set customerAdminGroupId field in create manifest when it is actually set

---

Makefile

reduces peak compile time memory usage by approx 1G - helps CI
```release-note
NONE
```

remove go build ./... from all target

---

env.example
hack/setup-rbac/main.go
pkg/fakerp/fakerp.go
pkg/fakerp/vault.go

note about vault permissions:
- we write to the vault using AZURE_CLIENT_ID
- we call EnrichWithVault in CreateOrUpdate using AZURE_CLIENT_ID
- we call EnrichWithVault in startup and sync using the master sp
Thus we need 2 permissions for the AZURE_CLIENT_ID (writer) and the master sp (reader)
```release-note
MSFT: support different master and worker service principals https://github.com/openshift/openshift-azure/pull/1226 has example role definitions which can be used for these.
```

use new master and worker service principals

---

pkg/fakerp/fakerp.go

```release-note
NONE
```
TODO: we need to monitor cluster create times properly

 increase deployment template timeout to 30 minutes, for when eastus is busy

---

test/e2e/standard/cluster.go

Noticed during my demo I was not propagating the errors up in the last
couple of steps, fixing that now
```release-note
NONE
```

Bubbling up errors properly

---

cmd/tlsproxy/tlsproxy.go

Allows us to have more granular control and more strict regexp.
Currently does not work if we want to use `^sutff` regexp
/cc @Makdaam @jim-minter 
```release-notes
NONE
```

etcd - move to path for checks

---

pkg/config/generate.go
pkg/fakerp/fakerp.go
pkg/util/random/random.go

At least for now, let's continue to use tags to determine which storage account is which, but this might help whoever browses the portal.
```release-note
NONE
```

add a convention for how we name storage accounts

---

docs/release.md

Add OSA release docs and instructions. Instructions were crafted from doing release manually for v1 and v2. 
Where is still a lot of automation missing, but we need to start somewhere.
cc @jim-minter

add release docs

---

hack/setup-rbac/main.go

```release-note
MSFT: add missing master role definition "Microsoft.Network/loadBalancers/backendAddressPools/join/action"
```

add missing role, needed for ILBs

---

pkg/arm/arm.go

```release-note
resolve bug whereby SAS URIs were not being calculated correctly during the vmss rotation procedure
```
fixes #1314

remove deepcopy otherwise sas uri not available when vmss are rotated

---

pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

```release-note
prevent update from succeeding unless cluster version matches v2.5
```

prevent update from succeeding unless cluster version matches v2.5

---

hack/upgrade-e2e.sh

We need to source early for monitoring shim to be able to pick the secrets.
Plus secret name changed after release repo refactor. 
```release-note
NONE
```

fix upgrade script ordering and secret name

---

pkg/plugin/plugin.go

@jim-minter this allows us to test upgrades in RunningUnderTest conditions. Otherwise, we can't test :)
Fixes: https://github.com/openshift/openshift-azure/issues/1322
```release-note
NONE
```

add runningUnderTest exclusion for upgrades

---

.gitignore

A symlink was being created to store azure secrets in `secrets`. This caused the working copy of the code to be detected as dirty. 
To fix this, we add `secrets` to .gitignore because git considers folder symlinks to be files.
fixes #1339 
```release-note
NONE
```
/cc @mjudeikis @jim-minter @Makdaam

Fix vmimage build commits being tagged as dirty in CI

---

cmd/monitoring/monitoring.go
hack/tests/upgrade-e2e.sh
pkg/api/config.go
pkg/api/converterfromplugin.go
pkg/api/converterfromplugin_test.go
pkg/api/types_test.go
pkg/config/config.go
pkg/config/v3/generate.go
pkg/config/v3/generate_test.go
pkg/config/v3/types.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go
pkg/util/structtags/structtags.go

```release-note
NONE
```
fixes #1350 
* Re-adds runningUnderTest which is a requirement for being able to update v3 clusters on v4.
* Fixes logic error whereby ConvertFromPlugin was updating the cluster to the latest version.
* Causes upgrade-e2e.sh to upgrade cluster by writing "latest" to plugin version.

re-add runningUnderTest to config blob for v3 compatibility

---

README.md

Some version of glide breaks the vendor folder and crashes when run.
```release-note
NONE
```

Warn about bad 'glide' tool.

---

pkg/cluster/kubeclient/ready.go

This should make the output of cluster create less wordy
```release-note
NONE
```

Slow the polling of WaitForReadySyncPod to 10 seconds

---

pkg/plugin/plugin.go

```release-note
make TestConfig optional in NewPlugin
```
requested by MSFT, backported to v3.2.1
(not going to update all of release to use v3.2.1 instead of v3.2...)

make TestConfig optional in NewPlugin

---

pkg/api/plugin/convertertointernal.go
pkg/api/plugin/convertertointernal_test.go
pkg/config/config.go
pkg/config/v3/generate.go
pkg/config/v3/generate_test.go
pkg/config/v4/generate.go
pkg/config/v4/generate_test.go
pkg/config/v5/generate.go
pkg/config/v5/generate_test.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go
pkg/util/mocks/mock_config/config.go
test/e2e/specs/fakerp/keyrotation.go

```release-note
* latch all configurables that come from the plugin config, such that a plugin config change won't cause unexpected cluster rotations
* secret rotation geneva action stub re-reads geneva certs from plugin config, among resetting a few other secrets
```

latch all configurables that come from the plugin config

---

test/e2e/standard/sanitychecker.go
test/e2e/standard/testapps.go

This PR exposes the logger so that the SanityChecker (that initialize various structs and the openshift client for testing) can be reused in isolated test.
```release-note
- E2E: standard exports the Log field from the SanityChecker for better reusability 
```

Export 'Log' from the SanityChecker struct.

---

cmd/monitoring/monitoring.go

```release-note
NONE
```
fix: https://github.com/openshift/openshift-azure/issues/1398
fix: https://github.com/openshift/openshift-azure/issues/1399 
remove chattiness and adds waits for race conditions

monitoring remove chattiness and race condition waits

---

pkg/cluster/hash_test.go

relax the hash test for the version under development otherwise we'll go mad

---

hack/tests/e2e-upgrade.sh
pkg/api/validate/admin.go

```release-note
make vm image configuration and individual container image configuration writeable via the admin API
```
@mjudeikis @asalkeld the testing is grotty here - Angus, I'm hoping the work you're doing will improve coverage across all the images; MJ it feels like we should end up with some sort of Go test suite around updates, but I'm not sure what that ends up looking like.

allow admin API to change image versions

---

Makefile

```release-note
NONE
```
When this make target was added in #1453, the azure namespacing was accidentally removed.

Fix secrets generation command

---

pkg/cluster/kubeclient/roundtrip.go
pkg/cluster/types.go
pkg/plugin/integration_test.go
pkg/util/azureclient/fake/accounts.go
pkg/util/azureclient/fake/cloud.go
pkg/util/azureclient/fake/codecov_dummy_test.go
pkg/util/azureclient/fake/compute.go
pkg/util/azureclient/fake/deployments.go
pkg/util/azureclient/fake/keyvault.go
pkg/util/azureclient/fake/storage.go
pkg/util/wait/wait.go

```release-note
NONE
```
The point of this is to have a deeper style of integration test that allows us to test the whole plugin with just azure and kube client fakes. We can then have greater confidence in what actions cause node rotations.

New fake azure client

---

hack/tests/e2e-upgrade.sh
test/e2e/specs/fakerp/setcontainerimage.go

```release-note
NONE
```
So @jim-minter we chatted about this earlier. I think this is a good incremental improvement.
from looking at the e2e tests, the admin action or createOrUpdate call is really minimal compared
with the setup and verify code. So I am not sure how the infrastructure that we talked about would save over just making use of the current e2e tests.

convert webconsole image change test to go

---

pkg/controllers/customeradmin/group_mapping.go
pkg/controllers/customeradmin/group_mapping_test.go

otherwise guest AAD user's don't work correctly (get #EXT# and more interposed in username)
```release-note
NONE
```
@asalkeld you were right about this, ptal ;-)

use mail attribute instead of userPrincipalName to map groups and users

---

pkg/api/validate/api.go
pkg/api/validate/api_test.go
pkg/api/validate/validators.go
pkg/api/validate/validators_test.go

```release-note
* don't output secret if validation fails
```
fixes #1494

don't output secret if validation fails

---

test/e2e/standard/cluster.go

In flakes we can see these can take just over 5mins
closes #1336
```release-note
NONE
```

Increase how long we wait for the loadbalancer to come up to 10s

---

test/e2e/specs/fakerp/admin.go
test/e2e/specs/fakerp/prometheus.go

```release-note
NONE
```
Looks like were e2e tests which were not run in some time because they lacked labels. This is a first step in making sure that a test is either run on every PR, or is part of a periodic run.

added [EveryPR] to Prometheus test, [LongRunning] to admin e2e test

---

Makefile

```release-note
NONE
```
When running ./hack/test/e2e-upgrade.sh I got an error:
```
+ make monitoring
go generate ./...
bindata.go
...
bindata.go
/bin/sh: 1: [[: not found
```
make will apparently use /bin/sh here, where [[ is not supported,
rather than /bin/bash. This change fixes this error.

Use shell-agnostic command for checking git tree

---

pkg/api/validate/plugin.go

```release-note
NONE
```
fix: https://github.com/openshift/openshift-azure/issues/1293
Revert of logging lock/validation

revert logging validation

---

pkg/fakerp/admin_handlers.go
pkg/fakerp/customer_handlers.go
pkg/fakerp/middleware.go
pkg/fakerp/util.go

```release-note
NONE
```
This is rather braindead, any better alternatives?

don't return 500s in the fakerp, only 400s - otherwise the client will retry

---

pkg/cluster/kubeclient/roundtrip.go
test/clients/openshift/client.go
test/e2e/standard/cluster.go
test/e2e/standard/sanitychecker.go

This configures the retrying round-tripper on the kubeclient used in e2e tests. In addition, http client used within `sanityChecker.checkCanAccessServices` is configured to use the retrying round-tripper.
Due to the fact that the retrying round-tripper requires a log instance, the `New*Client(cs)` functions in `test/clients/openshift/client.go` have been updated to accept an additional logger e.g. `New*Client(log, cs)`.
```release-note
NONE
```
closes #1438 
/cc @mjudeikis @jim-minter

enable retrying roundtripper in E2E openshift clients

---

pkg/api/validate/types.go
pkg/api/validate/types_test.go
pkg/api/validate/validators.go
pkg/api/validate/validators_test.go

```release-note
Validate cluster names to ensure they will comply with the DNS spec.
Validate location names to ensure they match the standard naming scheme.
```
Closes #1116.
This regex is sort of arbitrary; I followed MS' recommendation for domain name label best practices, except that I am allowing capital letters and a length of 2-63 characters. Happy to modify this as necessary.

Add validation for cluster names and locations

---

hack/vmimage.sh

```release-note
NONE
```
solves:
```
./hack/vmimage.sh
time="2019-04-23T06:44:57Z" level=info msg="vmimage starting, git commit v4.0-246-g3027211-clean"
time="2019-04-23T06:44:57Z" level=fatal msg="open secrets/client-key.pem: no such file or directory"
```

add secrets to vmimage

---

hack/artifacts.sh

This is because openshift uses a different leader and we can end up missing
the logs for the openshift controller.
```release-note
NONE
```

get all controller logs not just the leader

---

test/clients/openshift/project.go

```release-note
NONE
```
fixes #1436 
the log I saw which led me to this was `namespace_scc_allocation_controller.go:335] error syncing namespace, it will be retried: Operation cannot be fulfilled on namespaces "e2e-test-37of0": the object has been modified; please apply your changes to the latest version and try again`
@mjudeikis

wait for SCC annotation at project creation to avoid "no providers available to validate pod request" flake

---

test/e2e/specs/fakerp/admin.go
test/e2e/specs/fakerp/prometheus.go

```release-note
NONE
```
admin.go tested if a string pointer is not empty, changed to string.
Prometheus tests can't be run right after cluster startup. Cleaning up [EveryPR] tag for now.

removed [EveryPR] from Prometheus test, fixed admin.go test

---

hack/e2e.sh

```release-note
NONE
```
changing the default TIMEOUT for e2e tests instead of overriding it in the openshift/release repository in multiple places.

changing default e2e timeout to 60m

---

Makefile

Our Makefile uses the bash-specific [[ test construct, but GNU make defaults to using `/bin/sh` if a shell is not specified.[*] Hence, let's specify it.
[*]: https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html#index-shell_002c-choosing-the
This is a permanent fix for the problem previous patched in #1513 (and I see also #1098). It got reverted, I think by accident, in #1507.
Without this fix, I continue to get `/bin/sh: 1: [[: not found` errors.
```release-note
NONE
```

Set Makefile SHELL to bash

---

pkg/api/2018-09-30-preview/convertertointernal.go
pkg/api/2018-09-30-preview/default.go
pkg/api/2018-09-30-preview/default_test.go
pkg/api/2019-04-30/convertertointernal.go
pkg/api/2019-04-30/default.go
pkg/api/2019-04-30/default_test.go
pkg/fakerp/fakerp.go

```release-note
Set some default values (e.g. RouterProfile) when not specified upon creating a new cluster config
```
Addresses #336.

Add default values to external APIs

---

test/e2e/specs/customer_admin.go
test/e2e/specs/end_user.go
test/e2e/specs/osba_app.go
test/e2e/specs/scaleupdown.go

```release-note
NONE
```
Same as #1565 Reopening as a new PR due to github caching old tests as "required".

adding EndUser and ScaleUpDown to EveryPR

---

pkg/api/2018-09-30-preview/default.go
pkg/api/2018-09-30-preview/default_test.go
pkg/api/2019-04-30/default.go
pkg/api/2019-04-30/default_test.go

```release-note
Default MasterProfilePool count to 3 when not specified in new cluster configs
```
Addresses #336.
Note that the changes to each API version are identical.

Default MasterProfilePool count to 3

---

pkg/api/validate/admin.go

```release-note
check for role equality in admin update validation, otherwise an error occurs when attempting to admin update legacy clusters with only 2 infra nodes'
```

check for role equality in admin update validation

---

Makefile
hack/periodic/content-update.sh

```release-note
NONE
```
@jim-minter alternative POC for an automated script. I personally prefer golang one as it gives us more granular control. But at the same time, I can see simplicity here. WDYT?

Automatic content regeneration script

---

pkg/fakerp/admin_handlers.go
pkg/fakerp/config.go
pkg/fakerp/customer_handlers.go
pkg/fakerp/fakerp.go
pkg/fakerp/middleware.go
pkg/fakerp/routes.go
pkg/fakerp/server.go
pkg/fakerp/store/codecov_dummy_test.go
pkg/fakerp/store/store.go
pkg/fakerp/util.go
test/e2e/specs/fakerp/admin.go
test/e2e/specs/scaleupdown.go

```release-note
NONE
```
Refactor fake RP to use files as "storage"
Persist state into "storage" on methods
Split some of the methods where logic started to become overcomplicated.

fakerp refactor

---

pkg/api/2018-09-30-preview/default.go
pkg/api/2018-09-30-preview/default_test.go
pkg/api/2019-04-30/default.go
pkg/api/2019-04-30/default_test.go

```release-note
Add a default AgentPoolProfile with name and role "infra" when not specified in new cluster configs
Set default Count to 3 for the "infra" AgentPoolProfile
Set default OSType to Linux in AgentPoolProfiles
```
Addresses #336.

Add some default settings for AgentPoolProfiles

---

test/manifests/realrp/create.yaml

This is needed when running tests against the real rp. Otherwise the cluster creation fails validation:
```
charles@titan:~/Documents/go/src/github.com/openshift/openshift-azure$ FOCUS='\[Vnet\]\[Real\]' hack/tests/e2e-create-prod.sh
./hack/create.sh charles-terraform
INFO[2019-05-09T13:48:17+02:00] using region westeurope                      
INFO[2019-05-09T13:48:17+02:00] ensuring resource group charles-terraform    
INFO[2019-05-09T13:48:19+02:00] creating/updating cluster                    
FATA[2019-05-09T13:54:24+02:00] Code="TemplateValidationError" Message="OpenShift Managed Cluster validation failed with error: [invalid properties.routerProfiles[\"default\"]]" 
exit status 1
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec] …
```

Add default router profile to real rp sample manifest

---

hack/tests/e2e-prod.sh
test/sanity/sanity.go

- it doesnt need to call `make delete` because tests run against prod without access to kubeconfigs etc
- it doesnt need to call `make create` because the tests against the real rp already create a resource group and cluster as prereqs
- do not run the sanity package init logic if we are running a test against production TEST_IN_PRODUCTION=true
/cc @jim-minter @mjudeikis
```release-note
NONE
```
closes #1622

Fix the e2e prod script to avoid double creates and fakerp-esque deletes

---

hack/periodic/content-update.sh

```release-note
NONE
```
Add git status as somehow Ci runs and local runs produce different content. For compare.

add git status for clarity

---

test/clients/azure/client.go
test/e2e/specs/beforesuite.go
test/e2e/specs/fakerp/admin.go
test/e2e/specs/fakerp/clusterstatus.go
test/e2e/specs/fakerp/command.go
test/e2e/specs/fakerp/etcdbackuprecovery.go
test/e2e/specs/fakerp/forceupdate.go
test/e2e/specs/fakerp/keyrotation.go
test/e2e/specs/fakerp/loglevel.go
test/e2e/specs/fakerp/prometheus.go
test/e2e/specs/fakerp/reimagevm.go
test/e2e/specs/fakerp/setcontainerimage.go
test/e2e/specs/realrp/realrp.go
test/e2e/specs/realrp/vnetpeering.go
test/e2e/specs/scaleupdown.go

```release-note
NONE
```
Moving azure client (fake for now, since real e2e seems broken) to the sanitychecker singleton to keep it from reinitializing at every BeforeEach.
In the end the realRP client should also be in the singleton.

moved azure client init to BeforeSuite for reuse.

---

test/e2e/specs/realrp/realrp.go

Before GA, attempting to delete real rp cluster resources resulted in a `ScopeLocked` error with HTTP 409 response code.
The API now returns a `DenyAssignmentAuthorizationFailed` error with HTTP 403 as status code.
sample error: https://deck-ci.svc.ci.openshift.org/log?job=periodic-ci-azure-e2e-prod&id=20
/cc @Makdaam @mjudeikis
```release-note
NONE
```

Fix realrp test to check for new status code if resource deletes are attempted

---

test/e2e/specs/realrp/vnetpeering.go

This fixes the VirtualNetworkPeeringState check in the vnet peering e2e test against the real rp.
sample error: https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/20/build-log.txt
```release-note
NONE
```
/cc @mjudeikis @Makdaam @jim-minter

Fix VirtualNetworkPeeringState check in real rp vnet test

---

hack/verify/validate-generated.sh

This fixes the `validate-generated.sh` script which has caused `make verify` to fail locally for me, @Makdaam and maybe other members of the team.
This pins the version of go-bindata used to generate code in the temp directory created from the script to `41975c0`.
```release-note
NONE
```
/cc @Makdaam @mjudeikis

Pin go-bindata in validate-generated.sh

---

test/e2e/specs/fakerp/metricsbridge.go

This cleansup some imports in the metricsbridge e2e test
/cc @Makdaam 
```release-note
NONE
```

Cleanup imports in metricsbridge e2e test

---

pkg/fakerp/customer_handlers.go
pkg/fakerp/dns.go
pkg/fakerp/fakerp.go

Adds a fix to properly clean up NS records and add more debug logs so we see better what is happening with respect to dns record set updates/deletes.
closes #1655 
/cc @Makdaam @mjudeikis 
```release-note
NONE
```

Properly clean up cluster NS records from osadev.cloud dns zone

---

pkg/util/random/random.go

```release-note
NONE
```
Builds on #1595. Fixes #1662.

Reject vault names that contain MS reserved words

---

pkg/api/validate/api.go
pkg/api/validate/api_test.go
pkg/plugin/integration_test.go

```release-note
Properties.AuthProfile.IdentityProviders[x].Provider and Properties.AgentPoolProfiles[x].VMSize can now be changed by the user using CreateOrUpdate.
```
partial #1607

Make some api properties updatable

---

test/e2e/specs/fakerp/etcdbackuprecovery.go

making sure the backup variable is initialized before each run.
If the name of the backup is empty, fakeRP returns 404.
Fixes #1672 
```release-note
NONE
```

fixing etcdbackup test

---

test/clients/openshift/dumpinfo.go
test/e2e/specs/osba_app.go
test/e2e/standard/cluster.go
test/e2e/standard/sanitychecker.go
test/e2e/standard/testapps.go

```release-note
NONE
```
Adds basic event and logs gathering for pods for individual tests. This should help to identify cluster state during test failure instead of looking to artefacts at the end of execution where failure mode is already gone

individual artifact gathering on test failures

---

pkg/cluster/kubeclient/syncpod.go

This adds labels to the sync's service spec which in turn allows
targeting of the service by the sync's prometheus ServiceMonitor
```release-note
NONE
```

Add labels to sync's service spec

---

pkg/cluster/kubeclient/roundtrip.go
test/clients/openshift/client.go
test/e2e/standard/cluster.go

Moving these back to the default dial timeouts
```release-note
NONE
```

Default timeouts in RoundTrippers' http transports

---

pkg/sync/v6/bindata.go
pkg/sync/v6/data/Role.rbac.authorization.k8s.io/openshift-infra/prometheus-k8s.yaml
pkg/sync/v6/data/RoleBinding.rbac.authorization.k8s.io/openshift-infra/prometheus-k8s.yaml

The prometheus-k8s service account currently lacks the ability to list
endpoints, services and pods in the openshift-infra namespace.
```
[charles@akalugwu openshift-azure]$ kubectl auth can-i list services --as=system:serviceaccount:openshift-monitoring:prometheus-k8s --namespace=openshift-infra
no - no RBAC policy matched
[charles@akalugwu openshift-azure]$ kubectl auth can-i list pods --as=system:serviceaccount:openshift-monitoring:prometheus-k8s --namespace=openshift-infra
no - no RBAC policy matched
[charles@akalugwu openshift-azure]$ kubectl auth can-i list endpoints --as=system:serviceaccount:openshift-monitoring:prometheus-k8s --namespace=openshift-infra
no - no RBAC policy matched
```
This currently prevents instrumented apps in openshift-infra from being
scraped by a service …

Add a role for prometheus-k8s' serviceaccount to openshift-infra

---

hack/periodic/content-update.sh

This should fix the content update `make verify` flake which shows up
in the content update job from time to time.
The problem is that an older version of git is used in the ci-base image
(ci-base is used to run hack/periodic/content-update.sh) and the semantics
of `git add` is different in that version to what it is in version 2 with respect 
to deleted paths.
```
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like 'pkg/sync/v6/data/Template.template.openshift.io/openshift/eap71-amq-persistent-s2i.yaml' that are
removed from your working tree are ignored with this version of Git.
* 'git add --ignore-removal <pathspec>', which is the current default,
ignores paths you removed from …
```

Add --all flag to git add in content-update script

---

test/e2e/specs/fakerp/sync.go

```release-note
NONE
```
After #1543 is fixed enables the sync pod test on Every PR.
This will detect changes which cause sync pod to update a resource on every run.

enabling Sync pod test on EveryPR

---

Makefile
cmd/testinsights/codecov_dummy_test.go
cmd/testinsights/testinsights.go

```release-note
NONE
```
A command line tool which sends unit test results and durations to app insights.

send output from unit tests to app insights

---

test/e2e/specs/customer_admin.go

```release-note
NONE
```
This is needed because the test group has more members now:
```
Openshift on Azure customer-admin e2e tests [CustomerAdmin][Fake][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/customer_admin.go:25
should sync AAD admin group [It]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/customer_admin.go:235
Expected
<v1.OptionalNames | len:6, cap:8>: [
"ehashman@rhcuppettgmail.onmicrosoft.com",
"jgallego@rhcuppettgmail.onmicrosoft.com",
"jminter@rhcuppettgmail.onmicrosoft.com",
"ljakubow@rhcuppettgmail.onmicrosoft.com",
"mjudeikis@rhcuppettgmail.onmicrosoft.com",
"testuserdisabled@rhcuppettgmail.onmicrosoft.com",
]
to have length 1
```

Make the AAD sync test more robust

---

pkg/api/validate/types.go
pkg/api/validate/types_test.go
pkg/api/validate/validators_test.go

```release-note
Update cluster name validation to match ARM RG regex
```
Fixes #1753.

Update allowed cluster names to match ARM validation

---

pkg/api/validate/types.go
pkg/api/validate/types_test.go
pkg/api/validate/validators_test.go

```release-note
NONE
```
Cherry pick #1756 to release-v5 for v5.2.1 patch fix.

Update allowed cluster names to match ARM validation (cherry-pick)

---

pkg/api/plugin.go
pkg/cluster/types.go
pkg/cluster/update_master.go
pkg/config/config.go
pkg/config/v4/generate.go
pkg/config/v5/generate.go
pkg/config/v6/generate.go
pkg/fakerp/admin_handlers.go
pkg/fakerp/routes.go
pkg/plugin/plugin.go
pkg/util/azureclient/openshiftmanagedcluster/admin/client.go
pkg/util/mocks/mock_cluster/types.go
pkg/util/mocks/mock_config/config.go
test/e2e/specs/fakerp/carotation.go

Jira AZURE-198
```release-note
Microsoft: Add geneva actions for rotating certificates and certificatesAndSecrets.
```
The current implementation just rotates etcd certificates and support for the other certs will be added soon.

Add support for etcd ca rotation

---

hack/tests/origin-conformance.sh

This has caused our secrets to leak in CI. See https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-azure-master-e2e-azure-conformance.
We probably should rotate them asap.
```release-notes
NONE
```
/cc @thekad @mjudeikis @jim-minter
```release-note
```

Disable debug mode in conformance test script

---

hack/tests/ci-prepare.sh

Lock it down to prevent mishaps in the future. This should prevent leaking credentials even if accidentally pushing another script with -x in it.
```release-note
NONE
```

Avoid accidentally exposing secrets

---

hack/tests/origin-conformance.sh

Previously was go-get'ing ginkgo in this same function, but since moving
that to the ci-base image the bin directory is not automatically created
```release-note
NONE
```

Lost this directory along the way

---

pkg/api/plugin.go
pkg/api/validate/types.go
pkg/api/validate/types_test.go
pkg/cluster/kubeclient/backup.go
pkg/entrypoint/etcdbackup/etcdbackup.go
pkg/plugin/integration_test.go
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

```release-note
ETCD backups are now run prior to updating
```
Jira-263
@ehashman can you check the blobname validate. we currently create backup blobs with a "T" between the date and time.. I'd like to be consistent with how we do this

ETCD Backup before update

---

hack/tests/ci-prepare.sh
pkg/fakerp/aad.go
pkg/fakerp/client/config.go
pkg/fakerp/fakerp.go

```release-note
NONE
```
Stop re-using main secret for AAD sync and start using shared `aro-aad-shared` secret for this. This would limit the blast radius if the secret is leaked.

move to use dedicated aad sync application

---

hack/vmimage-validate.sh

Use the $IMAGE_RESOURCEGROUP variable instead of hard coded image group name
```release-note
NONE
```

Update vmimage-validate.sh to use the $IMAGE_RESOURCEGROUP instead of hard coded value

---

pkg/api/plugin/convertertointernal.go
pkg/api/plugin/convertertointernal_test.go

Closes #1828
```release-note
Bugfix: ensure that Geneva and PackageRepository certificates can be updated once set.
```

Make sure we can update Geneva and PackageRepository Secrets

---

cmd/vmimage/vmimage.go
hack/vmimage-validate.sh
pkg/vmimage/resources.go
pkg/vmimage/vmimage.go
pkg/vmimage/vmimage_test.go

We can now run `IMAGE_VERSION=latest IMAGE_SKU=osa_311 make vmimage-validate` to validate the latest published marketplace vmimage or `IMAGE_VERSION=311.129.20190810 IMAGE_SKU=osa_311 make vmimage-validate` to validate a specific version.
Jira ref: AZURE-326
```release-note
NONE
```

Allows make vmimage-validate to validate published marketplace vmimages

---

pkg/startup/v5/derive.go
pkg/startup/v6/derive.go
pkg/startup/v7/derive.go
pkg/startup/v8/derive.go
pkg/util/cloudprovider/cloudprovider.go
pkg/util/derived/derived.go
pkg/util/derived/derived_test.go

```release-note
- Disable DisableOutboundSNAT for VMSS
```
Prepare for https://github.com/openshift/openshift-azure/issues/1620
context: https://github.com/kubernetes/kubernetes/pull/74490
https://bugzilla.redhat.com/show_bug.cgi?id=1703512
This is preparation PR. We don't have code yet released as errata but this will enable us to configure this option when we get it fast.

add DisableOutboundSNAT for cloudconfig

---

pkg/api/plugin/convertertointernal.go
pkg/api/validate/admin.go
pkg/plugin/integration_test.go

closes #1873
```release-note
allow the following to be set using the admin API:
- SSHSourceAddressPrefixes
- SecurityPatchPackages
- ComponentLogLevel
```
/cc @jim-minter @ehashman

Make sure the allowed admin config update pass through

---

pkg/util/errors/errors.go
pkg/util/errors/errors_test.go

IsMatchingSyscallError() is currently not parsing a fully formatted url.Error. This PR makes this possible.
```release-note
NONE
```
closes #1400

make IsMatchingSyscallError() more flexible

---

pkg/fakerp/client/config.go
pkg/fakerp/clients.go
pkg/fakerp/customer_handlers.go
pkg/fakerp/fakerp.go
pkg/fakerp/vault.go

Tidy up the fakerp client creation and use of environment variables.
closes #1227
```release-note
NONE
```

fakerp: create clients in one place and use envconfig more

---

pkg/arm/v8/resources.go

```release-note
Enabling boot diagnostics means serial console logs are available as
well as serial console access.
```
Using the `config` storage account to store the boot diagnostics
information, since this SA is already present by the time ARM is
deployed

Enabling boot diagnostics on all VMSS

---

docs/e2e/requirements.md
docs/testing.md

```release-note
NONE
```
* Add Makefile targets `verify` to testing document
* Add additional supported FOCUSes to requirements
* Add `make secrets` to requirements for end-to-end testing 
* Format documentation

Document local testing 

---

pkg/vmimage/resources.go
pkg/vmimage/vmimage.go

```release-note
NONE
```
I got a successful build out this, but it failed the VM validation due to a token expiry.
/test vmimage

Avoid VM image build timeout

---

hack/tests/ci-prepare.sh
hack/vmimage-validate.sh
hack/vmimage.sh

So we can run it as a periodic job and get feedback from CIin form of a GitHub issue.
```release-note
NONE
```
/test vmimage

Adds CI notifications into vmimage-validate

---

CHANGELOG.md
pluginconfig/pluginconfig-311.yaml

```release-note
NONE
```
OpenShift container versions need to match the VM image. We determined we don't need to do a VM image update this sprint, and since the newest one doesn't match the container images we tested against, reverting back to 129 for now.

Update container versions for v8 release

---

pkg/sync/v9/sync_test.go
pkg/sync/v9/translate.go

populating the resourceGroupName in metrics-bridge config with the customer's resourceGroup name instead of the managed resourceGroup. 
```release-note
NONE
```

fixing RG in the metrics-bridge

---

Makefile
pkg/sync/v9/content_test.go

```release-note
NONE
```
Now make verify will catch these compile errors earlier.

Fix content_test.go after openshift/api update

---

cmd/createorupdate/createorupdate.go
pkg/util/aadapp/aadapp.go
pkg/util/azureclient/graphrbac/applications.go
pkg/util/mocks/mock_azureclient/mock_graphrbac/graphrbac.go

It is currently impossible to create 2 or more fakerp clusters and be able to log into any of the clusters apart from the latest one. This is because our fakerp cluster creation logic updates the reply urls of the AAD app to contain only the reply url of the last-created cluster. 
To reproduce the issue one can run the following series of steps
```
source ./env
export RESOURCEGROUP=charles-foo
make create
xdg-open https://openshift.${RESOURCEGROUP}.osadev.cloud
mv _data _data-${RESOURCEGROUP}
export RESOURCEGROUP=charles-bar
make create
xdg-open https://openshift.${RESOURCEGROUP}.osadev.cloud
```
After those steps, you are no longer able to login to `https://openshift.charles-foo.osadev.cloud` without updating the list of reply urls via the portal or cli
I want to be able to create …

Support multiple AAD reply urls per AAD App

---

pkg/api/validate/admin_test.go
pkg/api/validate/validators.go
pkg/plugin/integration_test.go

```release-note
MSFT: don't allow cluster creation with 2 infra nodes (azure-cli<=2.0.63 will stop working with openshift)
```
Verified that the azure-cli version recommended in documentation (v2.0.65)
https://docs.microsoft.com/en-us/azure/openshift/howto-setup-environment
already tries to create an openshift cluster with 3 infra nodes.
https://github.com/Azure/azure-cli/blob/azure-cli-2.0.64/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L2523

Not allowing 2 infra nodes anymore. Only accepting 3.

---

cmd/createorupdate/createorupdate.go
pkg/util/aadapp/aadapp.go

This is a follow-up to #1937. The patch api doesn't accept an empty slice for `identifiersUri` and therefore blows up in the case that a single cluster is linked to an AAD app, the cluster is deleted and the cluster is attempted to be unlinked from the AAD app.  This PR fixes that problem.
```release-note
NONE
```
/cc @mjudeikis @kwoodson

Fix multiple aad urls single-cluster case

---

hack/ci-notify/main.go

Removing sig-azure as assignee.  Will leave uncommented until we determine what we want to do in the meanwhile.  
Options:
- look up primary in the on call
- default list of assignees
```release-note:
None
```

Removing assignee from issue creation.

---

hack/vmimage-validate.sh

This is the reason why `periodic-ci-azure-vmimage-validate-osa311-latest` job currently fails (see https://github.com/openshift/openshift-azure/issues/1961#issuecomment-533894065).
Once the PR merged, the CI should pass sucessfuly if there are no security updates. If there are pending security updates, it will be failing and priting output of `yum updateinfo list security -q` into stderr. For example:
```
RHSA-2019:2829 Important/Sec. kernel-3.10.0-1062.1.2.el7.x86_64
RHSA-2019:2829 Important/Sec. python-perf-3.10.0-1062.1.2.el7.x86_64
```
```release-note
NONE
```

Fixes failure to cat yum_updateinfo_list_security log in make vmimage-validate

---

pkg/vmimage/ssh.go

Currently scap report and yum log files are not being cleaned up between `make vmimage-validate` runs. It's not an issue in CI, because we run jobs in clean environments, but can cause confusion when run locally because the validation will fail even if the image is valid. It happens because the command checks if files contain data or not.
Example scenario:
* You run validation locally and it fails due to pending security updates
* You fix the issue/update vm image
* You run validation locally again: it fails becasue `yum_updateinfo_list_security` log contains data from previous run
```release-note
NONE
```

Improves make vmimage-validate locally

---

test/e2e/specs/fakerp/setcontainerimage.go
test/e2e/standard/cluster.go

The test changes the image of the console deployment, which should cause
it to restart. we then do "validateCluster" - which is rather excessive, but the most often failure is that console is not available (which should not be suprising).
This PR does the following:
1. make a more focused check
2. wait longer for the console to be available.
```release-note
NONE
```
relates to flake #1438

Improve the validation of setcontainerimage

---

pkg/cluster/scaler/scaler.go
pkg/util/azureclient/compute/virtualmachinescalesets.go
pkg/util/azureclient/fake/compute/virtualmachinescalesets.go
pkg/util/mocks/mock_azureclient/mock_compute/compute.go

Add some diagnostics for the scale up flake: https://github.com/openshift/openshift-azure/issues/1410
```release-note
NONE
```

scale up debug: log the status of the scaleset and the activitylogs

---

hack/vmimage.sh

```release-note
NONE
```
Remove workaround as fix already merged

remove overrride

---

hack/setup-management/main.go
pkg/util/azureclient/fake/compute/virtualmachinescalesetvms.go
pkg/util/azureclient/network/privatelink/privateendpoint.go
pkg/util/azureclient/network/privatelink/privatelinkservice.go

Let's use explicit versions in our imports instead of `latest` alias. It will make SDK upgrades more predictable.
```release-note
NONE
```

Updates imports to use specific versions

---

hack/tests/verification-tests.sh

script for starting verification-tests  (Bushslicer) in CI, needed dependences have been added to the ci base image by a previous commit.
```release-note
NONE
```

CI test driver script for Verification tests

---

cmd/createorupdate/createorupdate.go

It seems like cluster deletion via `cmd/createorupdate/createorupdate.go` is currently broken. After deletion, the comand attempts to create a cluster again. For example, `make vmimage` fails on cleanup because cluster creation is happening in a non-existing resource group:
```
INFO[2019-10-17T13:23:02+01:00] deleting cluster
DEBU[2019-10-17T13:23:02+01:00]pkg/fakerp/middleware.go:16 pkg/fakerp.(*Server).logger.func1() starting: DELETE /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mradchuk-tests-1/providers/Microsoft.ContainerService/openShiftManagedClusters/mradchuk-tests-1?api-version=2019-10-27-preview
INFO[2019-10-17T13:23:02+01:00]pkg/fakerp/client/config.go:68 pkg/fakerp/client.newConfig() using region eastus …
```

Fixes cluster deletion via cmd/createorupdate/createorupdate.go

---

pkg/fakerp/fakerp.go

```release-note
NONE
```
With the roundtripper PR we seemed to have lost the return after a failed deploy.

return after deployment errors

---

hack/dev-version/dev-version.go
hack/dev-version/dev-version_test.go

```release-note
NONE
```
/cc @ehashman 
This situation is as follows:
we make a new minor release say 10.1, but don't have any sync/arm/config changes.
When we try and get the the latest versioned directory it breaks.

Fix the latest dev-version for minor releases that don't have a direcory

---

pkg/api/validate/validators.go
pkg/api/validate/validators_test.go
pkg/fakerp/fakerp.go

```release-note
NONE
```
Improvement in validation of the above two fields

Make sure both managementSubnetCIDR and PrivateAPIServer are provided together

---

pluginconfig/pluginconfig-311.yaml

```release-note
Update to [OpenShift 3.11.153](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-153)
```
/hold
VM image needs to publish over the weekend.

Update to OpenShift 3.11.153

---

cmd/createorupdate/createorupdate.go

This just looks like a copy-paste error. I have tested this locally and it fixes the problem.
```release-note
NONE
```
fixes #2035

fix master-e2e-create-20190430

---

hack/vmimage.sh

```release-note
NONE
```
This lets you export `IMAGE_RESOURCENAME` so you don't need to build a new image if you've done something silly that messed up the test cluster create or e2e, or if your e2e flakes.
Note: you may also need to set `AZURE_REGIONS` to ensure validation happens in the same region the test image was built.

Allow validation of an existing built image

---

hack/vmimage-validate.sh
hack/vmimage.sh

```release-note 
NONE
```
Frequent failures of [periodic vmimage build test](https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/periodic-ci-azure-vmimage) are due to mismatch between the region where image is stored and region where it is attempted to be used for validation. This PR sets `AZURE_REGION` and `AZURE_REGIONS` env variables to solve this issue.
In this test image is always created in `eastus`: https://github.com/openshift/openshift-azure/blob/e4245e59119cab8cfa8458c3f7557368ee62a525/cmd/vmimage/vmimage.go#L29. We don't pass location argument when running this command so the default value is used
After image is built, `vmimage.sh` calls `create.sh`, which invokes fakerp: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-azure-vmimage/189#1 …

Pin image location in vmimage test

---

pkg/api/2019-10-27-preview/converterfrominternal.go
pkg/api/2019-10-27-preview/convertertointernal.go
pkg/api/2019-10-27-preview/types.go
pkg/api/2019-10-27-preview/types_test.go

```release-note
Remove  PeerVnetID from 2019-10-27-preview API
```
Note microsoft will store the api that a cluster is created with and not allow a cluster to be updated
with an older version.

Remove PeerVnetID from 2019-10-27-preview API

---

Makefile
hack/verify/validate_pluginconfig.go
hack/verify/validate_pluginconfig_test.go

```release-note
NONE
```
/cc @ehashman
(easier than working around different python versions?)

Validate that VM and container versions of OCP match in pluginconfig (golang)

---

cmd/proxy/main.go

```release-note
NONE
```
Firstly, I have updated to Fedora 31 and have 
```
go version
go1.13.3 linux/amd64
```
The error I get is:
```
flag provided but not defined: -test.testlogfile
Usage of /tmp/go-build178558260/b625/proxy.test:
-cacert string
path to ca file (default "secrets/proxy-ca.pem")
-cert string
path to pem file (default "secrets/proxy-server.pem")
-key string
path to key file (default "secrets/proxy-server.key")
-subnet string
allowed proxy connect subnet (default "172.30.10.0/24")
FAIL	github.com/openshift/openshift-azure/cmd/proxy	0.032s
```

The init() in cmd/proxy is causing unit tests to fail

---

pkg/cluster/initialize.go
pkg/startup/startup.go
pkg/startup/v10/startup.go
pkg/startup/v11/startup.go
pkg/startup/v12/startup.go
pkg/startup/v7/startup.go
pkg/startup/v71/startup.go
pkg/startup/v9/startup.go
pkg/util/mocks/mock_startup/startup.go

This was removed in v10, but older clusters still need it. This part of the code
is heavily depended on by versioned code, but has not been versioned. This has
lead to a bug when scaling older clusters. https://github.com/openshift/openshift-azure/issues/1515
```release-note
NONE
```

Add ImagePullSecret back into older worker cs

---

Makefile

```release-note
NONE
```
Given we ignore fakerp in .gitignore I thought we should also clean it when make clean is run.

Remove /fakerp when running make clean

---

pkg/controllers/customeradmin/group_mapping.go
pkg/controllers/customeradmin/group_mapping_test.go

```release-note
Resolve customer-admin group memberships issue when case of AAD mail domain differs from case of AAD login
```

fix and extend e-mail matching in customer-admin-controller

---

pkg/sync/v13/sync.go

```release-note
NONE
```
cf https://github.com/openshift/openshift-azure/pull/1687

revert f66053121e8fd74acb6b40c0837471c3de5083f3 - it is a case study of premature optimisation

---

pkg/api/validate/types.go
pkg/api/validate/validators.go
pkg/api/validate/validators_test.go
pkg/plugin/integration_test.go

```release-note
MSFT: update plugin validator to reject upper-case domain names for public hostname and router.
```

don't allow upper-case domain names

---

pkg/entrypoint/admissioncontroller/scc.go
pkg/entrypoint/admissioncontroller/scc_test.go

```release-note
Fixes bug which prevented adding reconcile-protect annotation to SCCs
```

Allowing annotation openshift.io/reconcile-protect=true instead of a label

---

pkg/controllers/customeradmin/group_mapping_test.go

```release-note
NONE
```
This test, when applied against v12.2, fails (as seen in production), but passes against HEAD thanks to the fix in #2128. Hence it can be used to verify that the fixes in `release-v12-aad-hotfix` work as expected.

Add test for AAD group sync case 4 for non-guests

---

pkg/api/admin/converterfrominternal.go
pkg/api/admin/convertertointernal.go
pkg/api/admin/convertertointernal_test.go
pkg/api/admin/types.go
pkg/api/admin/types_test.go

Addming the `privateApiServer` field into the admin API makes debugging easier for an SRE: it is more obvious that the cluster has a private api enabled.
```release-note
NONE
```
/cc @mjudeikis

Adds privateApiServer field into the admin API

---

pkg/arm/v14/resources.go
pkg/fakerp/container_insights.go
pkg/startup/v14/startup.go
pkg/vmimage/vmimage.go

```release-note
NONE
```
This is because the template function will return interface{} on a non-existing
value instead of an error. With struct we get the error correctly.
This has hidden an error in the startup assets.

Fix Template() usage so bugs are not hidden

---

pkg/arm/arm.go
pkg/cluster/hash_test.go
pkg/config/config.go
pkg/startup/startup.go
pkg/sync/sync.go
pluginconfig/pluginconfig-311.yaml

We might not do a 14.1 point release but this was the easiest way to get the correct hashes for master.
```release-note
NONE
```

[release-v14] Freeze v14.0 hashes, bump plugin config to 14.1

---

hack/verify/validate-sec.sh

```release-note
NONE
```
note the "-u" is so that we can catch changes locally. In the v4 RP we are vendoring these tools. I am not sure if this is worth while here..

Fix verify-sec after upstream changes

---

pkg/api/validate/api.go

```release-note
add client id for use in unit tests which disables roleLister
```

add client id for use in unit tests which disables roleLister

---

pkg/api/validate/api.go
pkg/api/validate/api_test.go
pkg/api/validate/validators_test.go

```release-note
hide config from update return errors
```

make config struct invisible for update

---

cmd/createorupdate/createorupdate.go
hack/upgrade.sh
pkg/plugin/integration_test.go
test/manifests/fakerp/refresh-cluster.yaml

```release-note
NONE
```
Some changes in scripts/fakerp to make testing private cluster refresh easier

Testing private cluster rotation

---

pkg/api/validate/validators.go
pkg/api/validate/validators_test.go

```release-note
Intended as a soft launch support larger cluster creation based on previous performance tests now that the timeout issues for cluster creation of this size have been mitigated
```

node count increase

---

pluginconfig/pluginconfig-311.yaml

```release-note
Upgrade to [OpenShift 3.11.170](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-170)
```
New VM image and control plane containers.

Upgrade to OpenShift 3.11.170

---

pluginconfig/pluginconfig-311.yaml

```release-note
Upgrade to OpenShift [3.11.188](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-188)
```
/hold
VM image is still publishing.
This will unblock #2237.

Bump OpenShift version to 3.11.188

---

test/e2e/specs/fakerp/sync.go

```release-note
NONE
```
Currently, a ton of the e2e tests keep flaking because there's one remaining update during the sync runs that spill over from run 0 to run 1. (See e.g. #1778) I think that ignoring the 0th and 1st run will reduce the number of flakes we see from this.
/cc @jim-minter @asalkeld 
thoughts? 
Fixes. #1778.

Ignore second run of sync pod for updates

---

Makefile

Upstream changes in gosec keep breaking validation on builds. Since this
repo is in maintenance mode, I'd like to disable the checks.
```release-note
NONE
```

Disable gosec checks

---

pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

```release-note
Internal fix: no longer perform etcd-backup on upgrade
```
MS has been disabling this by commenting out:
https://github.com/openshift/openshift-azure/blob/c70152ea551524eb7470c19519d01a1d7035ea8d/pkg/plugin/plugin.go#L287-L293
To avoid leaving a dangling `backupEtcd` argument and an associated refactor to clean it up, I instead located everywhere that `createOrUpdateExt` is called and ensured that `backupEtcd` is always set to false. But I'm not attached to this solution, I could also just remove the code above.
Hopefully this will unblock upgrades on private clusters.

Disable etcd backups on upgrades

---

pluginconfig/pluginconfig-311.yaml

```release-note
Upgrade OpenShift to [3.11.232](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-232)
```
I also removed old pluginconfig versions. There are no v14 or 16.0 clusters in production; v18 was scrapped. There is currently one 15.0 cluster, and many and 16.1/17.0s.

Prep pluginconfig for v19 release

---

pkg/api/validate/plugin.go
pkg/api/validate/plugin_test.go

```release-note
If SecurityPatchPackages is not set, do not validate its corresponding certificate
```
@jim-minter note that I extremely lazily added a unit test case here because I did not think it was worth doing a refactor.

[release-v19] Disable SecurityPatchPackages certificate when feature isn't in use

---

CHANGELOG.md
pkg/arm/arm.go
pkg/config/config.go
pkg/startup/startup.go
pkg/sync/sync.go
pluginconfig/pluginconfig-311.yaml

```release-note
NONE
```
Needs to be merged after #2324 and #2322 and a v19.1 container image gets built so I can just update the pluginconfig.
I'm being a teeny bit fast and loose with the pluginconfig changes because v19.0 is never going to get deployed to production.
/hold

[release-v19] Prep v19.1
